### ISSUE TITLE
Improve metas for SEO

### ISSUE THREAD

**Issue by miguxbe** [flatpak/flatpak.github.io#1]
In order to get a well maintained metadata for SEO, I recommend to use the gem 'middleman-meta-tags' [1]. Is quite easy to use, just have to write key:value tags in the site.yml file and the helper does the hard work for you.

Of course, I can craft a patch for that as well, but first I need to know some extra info ;-)

[1] https://github.com/tiste/middleman-meta-tags

**Comment by jimmac** [comment]
I'm not sure this deserves another dependency. Seems like very little benefit. We can just add the appropriate meta tags in the layout file.
