### ISSUE TITLE
Document how best to manage a repository

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak.github.io#106]
There doesn't seem to be a good document on repository best practices (some of which may require the `ostree` command, some of which is up to `flatpak`). Stuff like: versioning (tagging versions you want to keep forever, vs. ones to delete), moving versions between branches, things like that. Basically how I'd approach FlatPak repo management, from a `reprepro` background.

**Comment by directhex** [comment]
https://github.com/flatpak/flatpak/issues/384#issuecomment-260630725 is also worth documenting

**Comment by allanday** [comment]
The docs have moved to a different repo. I've made a copy of this issue here:

https://github.com/flatpak/flatpak-docs/issues/15
