### ISSUE TITLE
http://flatpak.org/developer.html references gnome-dictionary 3.22.0 - inexisting

### ISSUE THREAD

**Issue by DimStar77** [flatpak/flatpak.github.io#107]
While working through the tutorial, trying to learn something, I followed:

http://flatpak.org/developer.html

When reaching the section about the Manifests, one falls into the trap that the published one does not work: gnome-dictionary-3.22.0.tar.xz does not exist (the latest version for gnome-dictionary is 3.20.0; even configure.ac in git does not have a higher version)

**Comment by allanday** [comment]
Looks to me like those examples use the 3.20 tarballs now.

**Comment by DimStar77** [comment]
```
wget https://download.gnome.org/sources/gnome-dictionary/3.22/gnome-dictionary-3.22.0.tar.xz

tar xvf gnome-dictionary-3.22.0.tar.xz

cd gnome-dictionary-3.22.0/
```

on the linked page

**Comment by DimStar77** [comment]
Also the manifests section still is about 3.22

![screenshot from 2017-02-02 14-27-20](https://cloud.githubusercontent.com/assets/532559/22551121/c2cc2012-e953-11e6-8846-565abf8a5ce6.png)

**Comment by allanday** [comment]
http://flatpak.org/developer.html is out of date (I actually just removed it). The docs are now hosted at http://docs.flatpak.org/, and to me they look like they have the right URLs.
