### ISSUE TITLE
Allow installing apps using .flatpak or .flatpakref files

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#111]
Downloading a .flatpak or .flatpakref allows installing an app without having to use the commandline, at least on recent Fedora. The apps page should allow installing apps using this method, since it is the best UX. However, this will require that:

1. The apps provide those files.
2. The page includes guidance on which distros and versions support installing in this way; maybe the page will also need a way for the user to say which distro & version they are on, and then show appropriate installation methods depending on that.

**Comment by nedrichards** [comment]
This is done now, right?

**Comment by allanday** [comment]
Yep.
