### ISSUE TITLE
Add a carousel with quotes from supporters 

### ISSUE THREAD

**Issue by jgarciao** [flatpak/flatpak.github.io#131]
I've seen that newstructure2017 branch has a nice list of logos of distros where flatpak will be _available_.  In the commits I've seen some changes about if they where also _supported_ or just available.

In addition to the actual list of logos, maybe a good way to show the supporters of flatpak could be a carousel with some nice quotes. Somethink like this [Responsive Quote Carouse](http://bootsnipp.com/snippets/featured/responsive-quote-carousel)

Recently Ikey Doherty from Solus talked very nicely about Flatpak in [Linux Unplugged](http://www.jupiterbroadcasting.com/106396/a-brisk-mate-for-solus-lup-181/). He also announced that they are adopting flatpak as their solution for distributing 3rd party apps

His quotes and some from Endless and others could fit well. If you like the idea I can try to create a partial or something to add it to the homepage.

**Comment by allanday** [comment]
I really like the idea of including quotes on the website - they're a great way of showing that Flatpak is a cool, exciting thing, that people are talking about positively. Jorge, would be interested in collecting some? We have a few in the press release we might be able to use.

I'm not really a fan of carousels and would prefer a static layout for the quotes, but that's a detail.

**Comment by jgarciao** [comment]
From the [Solus Announcement  - Adopting Flatpak ...](https://solus-project.com/2017/01/18/adopting-flatpak-to-reassemble-third-party-applications/)

- _We are adopting Flatpak to reassemble third party applications_
- _I’d like to personally thank Alexander Larsson of Red Hat, the chief developer of Flatpak, for the enthusiasm, honesty, and technical discussions we’ve had on these issues_

Talking on LINUX Unplugged 181:
- Begins talking about flatpak at 00:39:00  https://youtu.be/x9K2r0-BlRg?t=2341
- Explains why they chosed flatpak over snap 00:42:35 https://www.youtube.com/watch?v=x9K2r0-BlRg&feature=youtu.be&t=2555

LatenightLinux - [Episode 2](http://www.podtrac.com/pts/redirect.mp3/latenightlinux.com/media/LNL02.mp3)
- Begins talking about flatpak at 00:51:47
  - Solus is going to adopt Flatpak for 3rd party applications.
- Why flatpak and not snap? 00:56:25 
- Doesn't its feel like buying betamax? 01:05:49 

For what he wrote on the blog post and said in the podcast a summary quote could be:
_We are adopting Flatpak to distribute third party applications. Its technical merits and engaging team behind made us chose it over other alternatives_

Maybe we can just send him an e-mail and ask him for a quote

**Comment by ikeydoherty** [comment]
Flatpak is allowing Solus to future-proof our project in a way that aligns with both our core team and users. As well as the obvious advantages of distributing critical third party software, it is actively solving **current** issues such as multimedia and gaming for the masses, in a way that does not compromise the core concepts of sharing and security. This is further bolstered by an engaging, grounded upstream, who are actively readying desktop Linux for today, not just tomorrow.

**Comment by ikeydoherty** [comment]
Or yknow take one of the more natural less thought-out ones.. ^^

**Comment by jgarciao** [comment]
Thanks Ikey!

**Comment by allanday** [comment]
In terms of design, I think I'd favour 3/4 short and snappy quotes: "Flatpak is the future", "mature and stable", "technically superior", and so on.

**Comment by ikeydoherty** [comment]
@allanday those won't come from me as I can smell the marketing on them :D 

What I will say is "Future-proofing portability" or "The developer's choice for the user's choice"

"mature and stable" - it'll be mature when it has all the features in. It's making great progress, but we know it's not there on the integration front.
"technically superior" - is obviously a shot at competition, and a risky road, imho.

**Comment by allanday** [comment]
> @allanday those won't come from me as I can smell the marketing on them :D

Those were just examples! The idea would more be to let people talk about Flatpak (or find places where they already talking about it), and then cherry pick short sound bites.

**Comment by ikeydoherty** [comment]
Lol I know I'm just teasing :D I can see the importance of building on the brand and identity of Flatpak now. And for what its worth, it is the technically superior option. Low integration cost, with an instant high yield of opportunities. Other parties have a very strong brand identity, what I see is that Flatpak started with the technology first :]

**Comment by allanday** [comment]
The website now has quotes from supporters. The quotes could be better, but they do exist. :)

**Comment by jgarciao** [comment]
It looks very well. Thanks
