### ISSUE TITLE
FAQ: Explain "Note that bundles have some drawbacks, compared to a repository."

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak.github.io#134]
In reply to the question "Can I host my flatpak app on github?" we end the answer on a limb:

"Flatpak repositories can't (currently) be put on github in a convenient way. As an alternative, you can create a single-file bundle, and put that up on github as a 'release'. **Note that bundles have some drawbacks, compared to a repository.**"

I think it is a good opportunity to provide a convenient link here to some documentation which explains the concepts ("flatpak repositories", "single-file bundles") and elaborate further on the drawbacks of bundles compared to a repository.

**Comment by allanday** [comment]
This mentions the main disadvantage of using a single file bundle:

http://docs.flatpak.org/en/latest/distributing-applications.html#single-file-bundles

Do we really need this information in the FAQ? Seems more like a developer docs thing to me.

**Comment by bastianilso** [comment]
I suggested this because my impression was that many of the questions in the FAQ were directed towards developers. At least the following three:

"How does Flatpak relate to freedesktop.org technologies such as desktop files and appstream metadata?"
"Are there any IDEs that support Flatpak?"
"Can I host my flatpak app on github?"

**Comment by jimmac** [comment]
Closing this one, if you feel like the information needs more focus, feel free to reopen.
