### ISSUE TITLE
Getting FlatPak page lists requires >= Fedora 23, but installation directions conflict

### ISSUE THREAD

**Issue by MegFord** [flatpak/flatpak.github.io#141]
http://flatpak.org/getting.html states that Flatpak packages are available for >= Fedora 23, but the most recent package for Fedora 23 is FlatPak 0.6.12. The command line instructions (http://flatpak.org/apps.html) require FlatPak >= 0.6.13.

**Comment by jimmac** [comment]
As the current version of Fedora is 28, I bumped it to 24, even though I have no idea if that actually ships with a workable flatpak.
