### ISSUE TITLE
Website doesn't say how to install Flatpaks and SDKs

### ISSUE THREAD

**Issue by debarshiray** [flatpak/flatpak.github.io#142]
It seems that a bunch of information that used to be on flatpak.org isn't there any more. For example, how to install one of the GNOME stable Flatpaks, how to install the SDK, etc..

For what it's worth, my objective is to use the GNOME 3.22 applications and SDK on an OS that ships 3.20 (ie. Fedora 24).

**Comment by TingPing** [comment]
Should still be there, step one takes you to http://flatpak.org/getting.html to install flatpak, step two takes you to here http://flatpak.org/apps.html where you must follow the command line instructions for Fedora 24.

It just doesn't list every gnome project any more, perhaps because they don't have flatpakrefs nor are they really supported upstream for the most part.

**Comment by allanday** [comment]
> how to install one of the GNOME stable Flatpaks

It would be good to have those back, indeed. We need to figure out how to include them, since that page is mostly focused on apps with flatpakrefs.

> how to install the SDK,

Where is this missing from?

**Comment by debarshiray** [comment]
> Should still be there, step one takes you to http://flatpak.org/getting.html to install flatpak,
> step two takes you to here http://flatpak.org/apps.html where you must follow the
> command line instructions for Fedora 24.
>
> It just doesn't list every gnome project any more, perhaps because they don't have
> flatpakrefs nor are they really supported upstream for the most part.

I don't know what you meant by not "supported upstream". GNOME 3.22 is the latest stable GNOME. It seems strange to not be able to install the latest stable applications.

Secondly, I see that there was only gnome-builder.flatpakref until I added gnome-photos.flatpakref just now. Not sure what the story is here.

**Comment by debarshiray** [comment]
>> how to install the SDK,
>
> Where is this missing from?

I found http://flatpak.org/runtimes. I don't know how I arrived there. It mentions how to install the flatpakrepo, which is enough to install an application and get it running. There is no example about how to install an SDK.

**Comment by TingPing** [comment]
> I don't know what you meant by not "supported upstream". GNOME 3.22 is the latest stable GNOME. It seems strange to not be able to install the latest stable applications.

Plenty of applications in the gnome repo have never actually been used by their respective developers. So I think it makes sense on a project-by-project basis for a developer to request it be added personally.

**Comment by debarshiray** [comment]
> Plenty of applications in the gnome repo have never actually been used by their
> respective developers. So I think it makes sense on a project-by-project basis for
> a developer to request it be added personally.

 I agree that we should do a better job of maintaining the manifests, but somebody cared enough to add the JSON manifest. It seems strange to add a special status to the presence of a flatpakref to indicate that it is maintained.

If a manifest is present for an application and it is getting built, then we should ensure that users can easily (for some value of the term) install it. If the manifest is broken then we should fix it, and in the worst case remove it.

**Comment by allanday** [comment]
> how to install the SDK,
> 
>     Where is this missing from?
> 
> I found http://flatpak.org/runtimes. I don't know how I arrived there. It mentions how to install the flatpakrepo, which is enough to install an application and get it running. There is no example about how to install an SDK.

We used to have instructions there, and we could add them back, I suppose. The reason I removed them was that I was concerned about having documentation spread all over the website. Users shouldn't have to install runtimes themselves and it's probably something that developers should learn to do from the proper documentation.

**Comment by mkoura** [comment]
From point of view of someone totally new to Flatpak who want to install some app - I went to http://flatpak.org/apps.html, followed to http://flatpak.org/getting.html to make sure I have flatpak installed on my Fedora 25. Then I clicked on "download" button next to the app I wanted to install only to get "Not found org.freedesktop.Platform/x86_64/1.4" error message. Not very good user experience. Clicking randomly on links I finally got the info I needed at the bottom of http://flatpak.org/command-line.html

**Comment by allanday** [comment]
> From point of view of someone totally new to Flatpak who want to install some app - I went to http://flatpak.org/apps.html, followed to http://flatpak.org/getting.html to make sure I have flatpak installed on my Fedora 25. Then I clicked on "download" button next to the app I wanted to install only to get "Not found org.freedesktop.Platform/x86_64/1.4" error message. Not very good user experience. Clicking randomly on links I finally got the info I needed at the bottom of http://flatpak.org/command-line.html

Please file a new issue for that.

**Comment by allanday** [comment]
I think this issue is probably resolved now - the website has a clear path to flathub.org, which has a setup guide, and Flatpak will automatically install any needed runtimes.
