### ISSUE TITLE
Info on website about how to install flatpak is not complete - runtimes not mentioned

### ISSUE THREAD

**Issue by mkoura** [flatpak/flatpak.github.io#143]
Info about how to install app using flatpak should contain instructions for installing runtimes.

From point of view of someone totally new to Flatpak who want to install some app - I went to http://flatpak.org/apps.html, followed to http://flatpak.org/getting.html to make sure I have flatpak installed on my Fedora 25. Then I clicked on "download" button next to the app I wanted to install only to get "Not found org.freedesktop.Platform/x86_64/1.4" error message. Clicking randomly on links I finally got the info I needed at the bottom of http://flatpak.org/command-line.html

**Comment by alexlarsson** [comment]
What was the app?

**Comment by mkoura** [comment]
Skype

**Comment by mkoura** [comment]
The point is there should be info about how to add runtime repo
``flatpak remote-add --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo``
That info is buried at the bottom of http://flatpak.org/command-line.html and should be in install instructions.

**Comment by alexlarsson** [comment]
It should automatically find the runtimes, but I see there is an issue with the skype flatpakref. Will fix.

**Comment by alexlarsson** [comment]
Should be fixed now.

**Comment by mkoura** [comment]
Great, thanks!
