### ISSUE TITLE
Apps page layout breaks on mobile

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#147]
The grid of download buttons collapses down to a list on mobile, but one or two of the items are out of place. See:

![apps-mobile](https://cloud.githubusercontent.com/assets/213068/23941860/51a0a1c2-0962-11e7-91bb-606ef744d48f.jpg)

**Comment by jimmac** [comment]
And it only seems to do it on actual mobile screens. Scaling the window won't result in this :/
