### ISSUE TITLE
Inkscape not listed

### ISSUE THREAD

**Issue by Svetomech** [flatpak/flatpak.github.io#167]
Why is [official](https://inkscape.org/download/linux/) [Flatpak version](https://github.com/matze/inkscape-flatpak) of Inkscape not listed on the site? [It was](https://www.maketecheasier.com/assets/uploads/2016/07/unversal-packages-flatpak-repo-page.jpg), though.

**Comment by allanday** [comment]
> Why is official Flatpak version of Inkscape not listed on the site?

Because no one added it yet.

Looking at this, it seems that there's just a .flatpak file. Ideally we'd include a .flatpakref in order to setup a repository for the app.

>  It was, though.

That was a build from the nightly-graphics repo; something we're no longer recommending.

**Comment by Svetomech** [comment]
Got it.
