### ISSUE TITLE
The "Hello World" example does not work

### ISSUE THREAD

**Issue by gjsieben** [flatpak/flatpak.github.io#179]
The "Hello World" example does not work on Ubuntu 16.04.2 LTS.
http://flatpak.org/hello-world.html

If I perform all instructions, when running the final command, I instead get:
$ flatpak run org.test.Hello
execvp hello.sh: Permission denied

**Comment by TingPing** [comment]
Did you make `hello.sh` executable?

**Comment by gjsieben** [comment]
That's it. Perhaps this could be added, but really obvious...
