### ISSUE TITLE
Flatpak claims adherence to desktop standards

### ISSUE THREAD

**Issue by soc** [flatpak/flatpak.github.io#191]
Flatpak's [FAQ](http://flatpak.org/faq.html) claims the following:

> **How does Flatpak relate to freedesktop.org technologies such as desktop files and appstream metadata?**
> These standards are incorporated as mandatory parts in the flatpak definition. By relying on these standards we are building on years of investment and support under Linux.

This doesn't seem to be true.

One of the standards Flatpak violates is the XDG base directory spec: It incorrectly places files outside of the specified `XDG_CACHE_HOME`, `XDG_CONFIG_HOME`, `XDG_DATA_HOME` directories, by creating and populating a `.var` directory in `$HOME`.

I think the documentation could be improved by dropping the "freedesktop.org technologies such as ..." part, and explicitly listing both the standards adhered by Flatpak as well as those standards Flatpak chose to ignore.

I believe this could reduce user confusion as users might expect that an application formerly named `xdg-app` follows the same-named standard.

**Comment by TingPing** [comment]
Well the standards it mentions it uses. Another FAQ entry about `~/.var/app` would make sense.

**Comment by soc** [comment]
@TingPing What do you think about https://github.com/flatpak/flatpak.github.io/pull/192?

**Comment by matthiasclasen** [comment]
No. We are not 'violating' anything.

**Comment by soc** [comment]
Now I'm a bit baffled.

The spec clearly states where different files have to be placed. The Arch wiki even has a huge list of applications with associated bug reports to make them aware that dumping things into users' home folders is not the way to go anymore.

Flatpak clearly discards this and ignores the year-long efforts of reclaiming a user's home directory for the actual user, instead of it being a general dumping ground for application's private data.

Or am I misunderstanding something, and it's purely the word "violating" that should be adjusted a bit in your opinion?

**Comment by TingPing** [comment]
The spec says default locations that can be overridden with env vars. Flatpak overrides them in order to get portable and self contained applications.

**Comment by soc** [comment]
@TingPing Which env var does Flatpak override? On my system neither `XDG_CACHE_HOME`, nor `XDG_CONFIG_HOME` nor `XDG_DATA_HOME` are overridden, and I would strongly object to any application doing that without my permission. Still, a `.var` directory is obviously created and populated.

Whatever env var Flatpak uses to decide on the location of `.var`, it doesn't seem to use any of the ones specified above.

**Comment by TingPing** [comment]
> On my system neither XDG_CACHE_HOME, nor XDG_CONFIG_HOME nor XDG_DATA_HOME are overridden, and I would strongly object to any application doing that without my permission.

They are overriden in the sandbox not on the host.

>  Whatever env var Flatpak uses to decide on the location of .var, it doesn't seem to use any of the ones specified above.

Applications are sandboxed and have no access to `$HOME` so they get their own private directory to store things. The spec has nothing to do with this as it only defines the defaults.

**Comment by soc** [comment]
I'm not talking about sandboxed applications, I'm talking about Flatpak itself. Even if all sandboxed applications decided by their own free choice to write to `.var` that would be an issue of Flatpak.

**Comment by matthiasclasen** [comment]
The base dir spec is a recommendation for where desktop applications are meant to place their auxiliary files. flatpak is not a desktop application.

**Comment by matthiasclasen** [comment]
And even so, it is not a law that says you can't touch any other place. It just makes recommendations for common types of data applications might want to save to disk.

**Comment by matthiasclasen** [comment]
Yes, I'm mainly objecting to the term 'violate', here. Flatpak does follow the basedir spec where it makes sense, for example for the per-user repositories.

**Comment by soc** [comment]
> The base dir spec is a recommendation for where desktop applications are meant to place their auxiliary files. flatpak is not a desktop application.

This is incorrect, but a quite popular excuse.

> And even so, it is not a law that says you can't touch any other place. It just makes recommendations for common types of data applications might want to save to disk.

Exactly because the spec is poorly enforced, I would like to have it clearly documented, so that users like me can make a well-informed decision on whether to use Flatpak or not, without running into unwelcome surprises.

> Yes, I'm mainly objecting to the term 'violate', here. Flatpak does follow the basedir spec where it makes sense, for example for the per-user repositories.

Isn't this a bit like running into a speed trap and trying to argue that that the ticket should be dismissed because 90% of the time you followed the speed limit?

To be clear:

I'm not trying to question your implementation choices, I just like to have the choices that have been made – _as a matter of fact_ – to be clearly documented.

That's what the PR does.

**Comment by soc** [comment]
I adjusted the PR and replaced "violate" with "does not adhere to", hope it is fine this way!

**Comment by Lonsfor** [comment]
Maybe a better solution would be have a `flatpak` folder in `XDG_CACHE_HOME`, `XDG_CONFIG_HOME` and `XDG_DATA_HOME` with the application's data in its respective folder.

**Comment by TingPing** [comment]
@Lonsfor Applications can and do write arbitrary data outside of those directories. For example the Steam flatpak might contain a dozen subdirectories containing game data and configs from dozens of games that do their own thing.

**Comment by mjog** [comment]
A nice emergent property of the XDG spec is not only being able to back up all config files by simply archiving ~/.config, or being able to old cached files by "simply" deleting anything in ~/.cache older than n days, but also enabling software like backup apps being able to determine these locations programmatically, at runtime.

Flatpak's current behaviour breaks this, which kinda sucks. It's not as bad as being back in the bad old days of having to hunt-and-peck for these files on a per-app basis, but it does add back another location that now needs to be guessed by backup apps, etc.

**Comment by allanday** [comment]
I don't see anything that needs to be changed here, and the discussion has dried up, so closing.

**Comment by rokups** [comment]
A new [discussion](https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory/) popped up on reddit discussing applications littering `$HOME`. Participants generally agree that littering of user's home directory is undesirable. Please reevaluate location of `.var`. Especially if there is no good technical reason behind having it in `~/.var` as opposed to `~/.local/var`. Please consider convenience of your users.

**Comment by forteller** [comment]
I'm quite flabbergasted that a project so closely related to Gnome does not adhere to the best practice of freedesktop.org. I want a clean and smooth experience when using my computer. That's why I've chosen Gnome. I thought this was the general sentiment in the Gnome community. 

If there's an important reason to do it like this, then ok. But I can't seem to find any good reasons here. When so many people want you to change, to what must be said to be more "Gnome like", then it's strange that you don't consider it, or even seem to want to give us a good reason why not.

**Comment by alexlarsson** [comment]
The ~/.var/app location for per-application data as reached after a long discussion, including with some of the developers of the xdg basedir spec. We never got to updating the spec for this, but that will happen eventually.
