### ISSUE TITLE
Spotify link points to custom repository

### ISSUE THREAD

**Issue by cagatay-y** [flatpak/flatpak.github.io#194]
Applications page still lists link to Spotify from the custom repository, while [this post](https://blogs.gnome.org/alexl/2017/09/27/spotify-and-skype-flatpaks-moved-to-flathub/) says users should switch to Flathub build.

**Comment by AsciiWolf** [comment]
Is there any reason why Skype was not yet removed from the Applications page?

**Comment by TingPing** [comment]
I believe both @jimmac and @allanday agreed the apps page should just be removed and point to flathub's apps page.

**Comment by AsciiWolf** [comment]
Cool!
