### ISSUE TITLE
Website needs HTTPs

### ISSUE THREAD

**Issue by johnnyasantoss** [flatpak/flatpak.github.io#197]
Hello!

Why the Flatpak's website is using http and don't have a https version?
I mean, there's links to install applications through `.flatpakref` this shouldn't be using a insecure connection.

**Comment by jean-lourenco** [comment]
Yep, this is a must.
If the site is hosted on github pages with a custom domain, it's still possible to add https using a cloudflare free account.

**Comment by mwleeds** [comment]
This is a duplicate of #74
