### ISSUE TITLE
FAQ contradicts itself about systemd ties

### ISSUE THREAD

**Issue by smcmurray** [flatpak/flatpak.github.io#201]
The answers to these two questions contradict each other.

Is Flatpak tied to systemd?
==

No. Versions of flatpak 0.6.10 relied on systemd for cgroups setup, but this is no longer required.

Can Flatpak be used on servers too?
==

Flatpak is designed to run inside a desktop session and relies on certain session services, such as a dbus session bus and a systemd --user instance.

**Comment by TingPing** [comment]
Fixed by 73087f04bc5904a94354df6cde0d259b772a45b9
