### ISSUE TITLE
Flatpak.org uses the old spotify logo colour

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak.github.io#217]
Currently flatpak.org shows the following logo for Spotify (bottom right), you can also check in the source and see that #adcf00 is being used for green.

![screenshot from 2018-01-22 18-13-42](https://user-images.githubusercontent.com/3669750/35236683-0d99ef08-ffa0-11e7-900a-871fe2ca44ff.png)

However, Spotify design guidelines (https://developer.spotify.com/design/) state that #1DB954 should be used.
![spotify logo](https://developer.spotify.com/wp-content/uploads/2016/07/icon1@2x.png)

Also note that the logo that the spotify applicaiton uses in flathub is correct, it is only flatpak.org that is showing the old logo.

**Comment by jimmac** [comment]
Thanks for spotting. Fixed.
