### ISSUE TITLE
Selecting "Home" in the footer on press page takes you to the press page, not home

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak.github.io#219]
From the press page [0], if one scrolls to the bottom and selects "Home" in the footer, this in fact links to [1] not the root of the site [2]. Therefore the user is taken back to the page they were viewing rather than the home page.

Note: I assume this link it just taking the parent folder and not the root page of the site, so as the press pages are done as a subfolder this breaks.

0 - https://flatpak.org/press/2016-06-21-flatpak-released.html
1 - https://flatpak.org/press/
2 - https://flatpak.org/

**Comment by jimmac** [comment]
Thanks for spotting.

**Comment by ahayzen** [comment]
@jimmac also noticed the main "FLATPAK" at the top left has the same issue. Does your commit fix this ? Or does this need a separate fix ?
