### ISSUE TITLE
Show more app logos

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#221]
The point of showing app logos on the home page is to:

 * Demonstrate that Flathub has lots of apps
 * Demonstrate that Flathub has good apps that people are familiar with
 * Allow a visitor to see a logo for an app that they might want to install

Showing more logos would achieve these goals better than the 6 that are being shown right now. [The mockups I did](https://raw.githubusercontent.com/flatpak-design-team/flatpak-website-mockups/master/flatpak.org.png) show 16.

**Comment by jimmac** [comment]
So going through the listed apps we have now, excluding less familiar ons and those with terrible icons (such as Audacity), here's what I came up with:

Discord
Geary
Gitg
GNOME Twitch
Inkcape
Libreoffice
Mypaint
Peek
Picard
Signal
Slack
Steam
Viber
VLC

That's 20 icons I don't feel bad about putting on the landing page. Do you want to mark the 4 for elimination?

**Comment by allanday** [comment]
I hate to be the one saying this, but I'm generally more concerned with the brand recognition of each app rather than how pretty it looks - a collection of iffy icons that people recognise is going to do us more favours than a set of pretty icons that aren't known.

On that basis, the most dubious icons from the above list are probably:

 * Discord
 * Geary
 * Gitg
 * GNOME Twitch
 * Peek
 * Picard
 * Viber

Ones you don't have that I'd be keen to see on the page include:

 * Telegram
 * Atom
 * Darktable
 * Spotify
 * Google Play Music
 * Blender
 * GIMP
 * Skype
 * VLC
 * Transmission
 * Kdenlive

**Comment by TingPing** [comment]
@allanday Discord is a very popular application.

**Comment by allanday** [comment]
I think this got fixed.
