### ISSUE TITLE
Add redirects for removed pages

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#222]
Commit 6a4b7c90c36 removed command-line.html and apps.html. Anyone following old links to those pages, or following their browser history to them, will hit a (not very nice - see issue 220) 404 page.

It would good if we could automatically redirect users somewhere useful.

**Comment by jimmac** [comment]
Needs nginx configuration redirection to work on the deployed site.

**Comment by allanday** [comment]
Rob fixed this.
