### ISSUE TITLE
Add elementary OS to /getting.html

### ISSUE THREAD

**Issue by orschiro** [flatpak/flatpak.github.io#225]
Since Linux Mint is also mentioned separately, can we add the popular elementary OS on https://flatpak.org/getting.html?

**Comment by allanday** [comment]
> Since Linux Mint is also mentioned separately, can we add the popular elementary OS on https://flatpak.org/getting.html?

Sure! Do you know what instructions are required?

**Comment by TingPing** [comment]
I *think* its the exact same as Ubuntu, Mint is separate because they support it out of the box.

**Comment by TingPing** [comment]
As I said, Mint has its own section because they have Flatpak installed out of the box so it has different instructions.

**Comment by orschiro** [comment]
@TingPing yes. What do you think of 

> . What if we write "Ubuntu and derivatives"?

**Comment by allanday** [comment]
> What if we write "Ubuntu and derivatives"?

We're in the process of redesigning the websites, and the new design will have [per-distro setup tutorials](https://raw.githubusercontent.com/flatpak-design-team/flatpak-website-mockups/master/flatpak-setup-wires.png), so I don't think that would work.

**Comment by orschiro** [comment]
> We're in the process of redesigning the websites, and the new design will have per-distro setup tutorials, so I don't think that would work.

Ah, that's great. I guess that will solve my request. :-)
