### ISSUE TITLE
Collect flatpak presentations

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#232]
We should start collecting the various flatpak talks and presentations we've given over the years in a central place.

**Comment by matthiasclasen** [comment]
Jens Petersen, FUDCon APAC 2016 in Phnom Penh,
https://www.slideshare.net/JensPetersen2/flatpak-introdiction

Alexander Larsson, foss-north 2017, Gothenburg,
https://www.youtube.com/watch?v=xIjxNtIwcBA

Mario Sanchez Prada+Richard Hughes, at Samsung Research, Staines, UK, March 2017,  
https://speakerdeck.com/mariospr/the-future-of-linux-application-distribution-ostree-flatpak-and-gnome-software

Matthias Clasen, devconf.cz, January 2017, Brno,
https://mclasen.fedorapeople.org/devconf-flatpak.pdf

**Comment by allanday** [comment]
I can add a page for this, but where should we link to it from? The only place I can think of is the footer.

**Comment by matthiasclasen** [comment]
footer seems fine to me

**Comment by matthiasclasen** [comment]
I should refresh that list with some presentations from 2018

**Comment by allanday** [comment]
The link for Alex's 2017 All Systems Go presentation is currently broken: https://cfp.all-systems-go.io/en/ASG2017/public/events/114

**Comment by allanday** [comment]
I've created a page with the list here: https://github.com/flatpak/flatpak.github.io/tree/presentations

I think we should make sure that there are some more recent presentations listed, before we put it on the site.

**Comment by matthiasclasen** [comment]
thanks

**Comment by ramcq** [comment]
https://2018.guadec.org/pages/talks-and-events.html#abstract-41-flathub__an_app_store_and_build_service_for / https://www.youtube.com/watch?v=Hga20qlyknw / https://docs.google.com/presentation/d/1vTiX0iUgA5UAu5OiJctVsFJE4KzNoaa1oi5fg5n5_Jk/edit?usp=sharing

**Comment by matthiasclasen** [comment]
https://people.gnome.org/~alexl/presentations/las-gnome-2018.odp
https://people.gnome.org/~alexl/presentations/all-systems-go-2018.odp

**Comment by allanday** [comment]
> https://people.gnome.org/~alexl/presentations/las-gnome-2018.odp
> https://people.gnome.org/~alexl/presentations/all-systems-go-2018.odp

I'll maybe turn these into PDFs and host them on flatpak.org itself.

**Comment by felipeborges** [comment]
https://www.linuxdays.cz/2018/video/Jiri_Janousek-Why_I_switched_to_Flatpak.pdf
https://docs.google.com/presentation/d/1CNxdE30cSLE7wFE6zlgMmuKWjygba91FG2YHsb9clmc/edit?usp=sharing
https://www.youtube.com/watch?v=EdrSJMKikUM

**Comment by mwleeds** [comment]
> https://www.linuxdays.cz/2018/video/Jiri_Janousek-Why_I_switched_to_Flatpak.pdf https://docs.google.com/presentation/d/1CNxdE30cSLE7wFE6zlgMmuKWjygba91FG2YHsb9clmc/edit?usp=sharing https://www.youtube.com/watch?v=EdrSJMKikUM

I added these to the list, except the docs link which doesn't work any more. Let's close this issue and add any more we find via issues or PRs.
