### ISSUE TITLE
Support for HTTP_PROXY

### ISSUE THREAD

**Issue by hellweiss** [flatpak/flatpak.github.io#233]
Please add support for HTTP_PROXY with Authentication
eg:
export HTTP_PROXY=http://proxyuser:proxypassword@proxy.domain.com:3128/
export HTTPS_PROXY=http://proxyuser:proxypassword@proxy.domain.com:3128/

Or as apt and yum do in apt.conf and yum.conf
Perhaps I am doing something wrong.

Thank you

**Comment by TingPing** [comment]
This sounds like you meant to report it against flatpak/flatpak?

**Comment by hellweiss** [comment]
Oops. Right.
