### ISSUE TITLE
Land the quick-setup branch

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#234]
Things that are left to do before we can land the quick-setup branch:

- [x] On the quick setup page, the distro logos are a bit big and far apart - it would be nice to reduce the need to scroll
- [x] It might be good to rename the `quicksetup` page name to `setup`? (One word is nicer than two, and the quick is somewhat superfluous to navigation.)
- [x] There ought to be a redirect from the existing `getting.html` page to `setup.html`, or whatever we end up calling it.

**Comment by jimmac** [comment]
I've updated the landing page in the meantime, or does it still feel too wide?

**Comment by allanday** [comment]
> I've updated the landing page in the meantime, or does it still feel too wide?

Was width the issue? I can't remember.

I'd like to ensure that the developers section isn't below the fold. Maybe it would make sense to increase the number of columns and reduce the number of rows?

**Comment by jimmac** [comment]
We're good to go from my POV.

**Comment by allanday** [comment]
> We're good to go from my POV.

Go go go!

**Comment by jimmac** [comment]
I've deployed to github, needs to be deployed to front now. The flathub side is ready for deployment once this happens.

**Comment by allanday** [comment]
Thanks @jimmac !
