### ISSUE TITLE
active vs inactive icon grid

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#238]
There's icon grids on the front page where I learn (to my frustration) that clicking the icons does nothing. Then I go to the quick setup page and have to unlearn this.

**Comment by jimmac** [comment]
That's a fair point. Personally I'd drop the distro grid completely from the landing page. Either dropping graphical element completely or going wh the stencil penguin? What do you think, Allan?

**Comment by allanday** [comment]
> That's a fair point. Personally I'd drop the distro grid completely from the landing page. Either dropping graphical element completely or going wh the stencil penguin? What do you think, Allan?

One of the key pieces of information that the home page needs to communicate is that Flatpak is cross-distribution. The logos are a good way of doing that and they draw plenty of attention. They also help to communicate a general sense of support and engagement.

Is there a particular reason to drop the logos?

**Comment by jimmac** [comment]
We have two competing grids close. Visually neither takes dominance. And you mentioned developers being behind the fold in another bug. Combined with the conflicting behavior of the distro logos on the landing page and setup page I'd rather see grid presentation of the apps and do something different for distros. I'll try to provide a mockup.

**Comment by allanday** [comment]
> We have two competing grids close.

Yeah, that's true. It's not very beautiful, but it does kind of work in terms of content. I suck at web design.
