### ISSUE TITLE
consolidate redirects in one place

### ISSUE THREAD

**Issue by ramcq** [flatpak/flatpak.github.io#241]
The nginx.conf for flatpak.org has these "baked in", it would be better to keep them all in one place in the redirects defined by Middleman:
```
location /apps.html {
    return 301 https://flathub.org/;
}
 
location /hello-world.html {
    return 301 http://docs.flatpak.org/en/latest/getting-started.html;
}
 
location /runtimes.html {
    return 301 http://docs.flatpak.org/en/latest/available-runtimes.html;
}
```

**Comment by jimmac** [comment]
If we do it in middleman we'll lose the 301 header though? https://middlemanapp.com/basics/redirects/

**Comment by ramcq** [comment]
Ok, send me the extra redirects you need in nginx and kill them out of middleman then? :)

**Comment by jimmac** [comment]
This is what we have in config.rb now:

redirect "press/index.html", to: "press/2016-06-21-flatpak-released.html"
redirect "developer.html", to: "http://docs.flatpak.org"
redirect "getting.html", to: "/setup/"
