### ISSUE TITLE
Text on 404 doesn't seem right

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#247]
The heading says OOPS, then below it says "The page you're looking for is no longer there."

The oops feels a bit like it's shouting. Also, there are other reasons for people hitting a 404, other than pages being moved.

Perhaps a simple "Sorry, that page can't be found." might be better?

Or, we could riff off the flat pack reference and do something like:

"Confused? Maybe you should [start at the beginning](https://flatpak.org)."

**Comment by jimmac** [comment]
Are you giving me options? You should know better :)
