### ISSUE TITLE
add a blog

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#250]
we can either just collect links to people's blog posts on flatpak and related topics from elsewhere, or set something up for dedicated posts on flatpak.org.

**Comment by allanday** [comment]
One option would be to use an external platform to host the blog, like Medium. We'd need to make sure that potential contributors would be comfortable using this though.

**Comment by matthiasclasen** [comment]
i guess this just didn't pan out. Instead, its just mine and alex' personal blogs
