### ISSUE TITLE
collect ideas for flatpak blog topics

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#251]
If we add a blog, it would be good to make sure we have a sufficient supply of posts. One way to help with this would be to collect a list of suitable topics and reach out to prospective writers.

Another would be to look at Alex or Matthias blog and look at republishing some of the better material
from there.

**Comment by matthiasclasen** [comment]
https://blogs.gnome.org/alexl/
https://blogs.gnome.org/mclasen/

**Comment by allanday** [comment]
Ideas for posts:

 - Example tutorials - "how I flatpaked foo"
 - High-level plans and progress - where's Flathub heading, adoption statistics
 - Overcoming build common issues / tips and tricks
 - Under the hood - technical details of how Flatpak works (need to be careful to pitch this at the right level)
 - Sandboxing and privacy - why it matters, what we're doing, what the missing pieces are
 - Benefits to developers - how Flatpak helps with QA, bug reporting, testing

**Comment by TingPing** [comment]
I've made a few blog posts also: https://tingping.github.io/

**Comment by matthiasclasen** [comment]
I think we should just make a page linking to existing blog posts, or maybe make it part of the page that is going to list talks, articles and the like.

**Comment by matthiasclasen** [comment]
Here is more, from 2018:

https://blogs.gnome.org/mclasen/2018/07/02/flatpak-in-detail-part-3/
https://blogs.gnome.org/mclasen/2018/07/07/flatpak-making-contribution-easy/
https://blogs.gnome.org/mclasen/2018/07/14/the-flatpak-bof-at-guadec/
https://blogs.gnome.org/mclasen/2018/07/19/flatpak-a-look-behind-the-portal/
https://blogs.gnome.org/mclasen/2018/08/03/flatpak-portal-experiments/
https://blogs.gnome.org/mclasen/2018/08/26/about-flatpak-installations/
https://blogs.gnome.org/mclasen/2018/09/07/on-flatpak-dependencies/
https://blogs.gnome.org/mclasen/2018/10/08/flatpak-after-1-0/
https://blogs.gnome.org/mclasen/2018/11/26/an-update-on-flatpak-updates/
https://blogs.gnome.org/mclasen/2018/12/19/flatpak-commandline-design/
