### ISSUE TITLE
Arch setup guide page lacks adding flathub remote step

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak.github.io#255]
All the other distros seem to have this step.

**Comment by alexlarsson** [comment]
Or does arch have this pre-configured?

**Comment by aleb** [comment]
Maybe add "sudo" in front of the command. Also missing from the Ubuntu instructions.

**Comment by allanday** [comment]
> Or does arch have this pre-configured?

We have [a comment](https://github.com/flatpak/flatpak.github.io/blob/source/data/distro.yml#L116) that indicates that...

**Comment by aleb** [comment]
I previously remote-delete flathub and allthe other remotes and uninstalled flatpak. Then I reinstalled flatpak but flathub was not there, I had to add it manually.

**Comment by TingPing** [comment]
Every install (not upgrade) will add the remote: https://git.archlinux.org/svntogit/packages.git/tree/trunk/flatpak.install?h=packages/flatpak#n1

**Comment by aleb** [comment]
You could add a step "Run `flatpak remotes` to make sure the "flathub" remote is registered."
