### ISSUE TITLE
Freedesktop.org Application Platform version 1.6 stopped working Fedora 27 

### ISSUE THREAD

**Issue by TheRoarkster** [flatpak/flatpak.github.io#257]
Running Fedora 27 (4.15.17-300.fc27.x86_64 kernel).  After recent update, all of my flatpak applications stopped working.  

For the application itself "Freedesktop.org Application Platform version 1.6," I get the error `failed to get related refs: using origin flathub mkdir(summaries): No such file or directory`.
![screenshot from 2018-04-21 09-06-53](https://user-images.githubusercontent.com/35146738/39086326-96ea5ba0-4544-11e8-92f6-c2ef359efe6d.png)
For a flatpak application, I get the error `failed to get related refs:[system/flatpak/flathub/desktop/org.signal.Signal.desktop/stable] mkdir(summaries): No such file or directory`.  

![screenshot from 2018-04-21 09-04-08](https://user-images.githubusercontent.com/35146738/39086328-98d5e1b4-4544-11e8-8688-dec95ffb7643.png)

Any ideas what happened here?  After this issue arose, I made the mistake of trying to reinstall the Freedesktop.org Application.  Now I can't get it reinstalled and none of the apps work.

**Comment by TingPing** [comment]
This should be reported against flatpak: https://github.com/flatpak/flatpak

**Comment by TheRoarkster** [comment]
Thanks @TingPing.  Should I delete this one then?

**Comment by TingPing** [comment]
It is already closed.
