### ISSUE TITLE
Remove Google Analytics and others Google trackers

### ISSUE THREAD

**Issue by yannicka** [flatpak/flatpak.github.io#261]
Both [Flatpak](https://flatpak.org/) and [Flathub](https://flathub.org/) have Google Analytics. This is a privacy issue.

Could you remove it and replace it by nothing or by something like [Matomo](https://matomo.org/)?

In the same way, would it be possible to use host fonts instead of Google Fonts?

And, finally, would it be possible to host images instead of using googleusercontent.com?

**Comment by TingPing** [comment]
Flathub website is tracked here btw: https://github.com/flathub/linux-store-frontend

**Comment by Zig-03** [comment]
> Both [Flatpak](https://flatpak.org/) and [Flathub](https://flathub.org/) have Google Analytics. This is a privacy issue.
> 
> Could you remove it and replace it by nothing or by something like [Matomo](https://matomo.org/)?
> 
> In the same way, would it be possible to use host fonts instead of Google Fonts?
> 
> And, finally, would it be possible to host images instead of using googleusercontent.com?

Thanks for opening this issue. I really hope the devs will start listening to your suggestion, privacy needs to be taken seriously.

**Comment by refi64** [comment]
Don't most people who are privacy-conscious regarding stuff like this use a blocker?

**Comment by catastrop** [comment]
>Don't most people who are privacy-conscious regarding stuff like this use a blocker?

No. The developer should concern about user's privacy.

**Comment by catastrop** [comment]
It's about a year ago this issue was created. But the maintainers haven't remove google analytics. Why?

They could use Matomo.

**Comment by catastrop** [comment]
there is also this one

https://github.com/usefathom/fathom

**Comment by barthalion** [comment]
Google Analytics was replaced with Matomo.

**Comment by Zig-03** [comment]
> Google Analytics was replaced with Matomo.

FlatHub is still using Google Analytics, along with other potential trackers such as googleusercontent.com.

**Comment by barthalion** [comment]
That's true, but it's tracked separately over at linux-store-frontend repo at Flathub org on GitHub.
