### ISSUE TITLE
App icons missing on Firefox

### ISSUE THREAD

**Issue by jurf** [flatpak/flatpak.github.io#262]
Firefox:
![snimka obrazovky z 2018-04-29 17-27-49](https://user-images.githubusercontent.com/7472425/39408161-ccb89532-4bd2-11e8-8f17-60653d9dc275.png)

Chromium:
![snimka obrazovky z 2018-04-29 17-29-47](https://user-images.githubusercontent.com/7472425/39408177-f4e8b816-4bd2-11e8-84d7-d96235c34223.png)

And while we’re at it, it’s quite confusing if they’re not click-able.

**Comment by TingPing** [comment]
Fine here on Firefox 59.0.2.

**Comment by jurf** [comment]
Same here, +Fedora 28. Still happens, though when I tried for the first time today, several more icons appeared, then I tried Ctrl+F5 to clear the cache and it went back. Works fine on mobile on the same network.

**Comment by jurf** [comment]
Also works fine on Firefox Nightly, though I did notice that the icons that display on 59 are also the first to load…

**Comment by jurf** [comment]
Still an issue. What is even happening.

**Comment by jurf** [comment]
![obrazok](https://user-images.githubusercontent.com/7472425/45902752-d5fca700-bde7-11e8-9992-323916ec0c85.png)

What even…?

**Comment by matthiasclasen** [comment]
it works in my firefox. Please reopen if its still an issue

**Comment by jurf** [comment]
Well, did some debugging, turns out the issue was [Privacy Badger](https://www.eff.org/privacybadger) blocking access to [flathub.org](https://flathub.org); I reported the issue.
