### ISSUE TITLE
Add instructions for Pop!_OS

### ISSUE THREAD

**Issue by cassidyjames** [flatpak/flatpak.github.io#264]
Pop!_OS is a GNOME-based distro built on Ubuntu, shipped by default on System76 computers. However, it does not use GNOME Software. The installation instructions would be similar to the Ubuntu ones, but not quite the same. Adding instructions for Pop!_OS users would help them get started since it may not be obvious which parts of the Ubuntu instructions to follow, and which to omit.

**Comment by TingPing** [comment]
It is just rebranded right? What is the name of the package?

**Comment by cassidyjames** [comment]
No, it does not use GNOME Software or anything forked or based on it. It uses Pop!_Shoo, which is an AppStream and PackageKit app store based on elementary AppCenter. It does not currently have any Flatpak integration, so that part is irrelevant.

**Comment by cassidyjames** [comment]
This would basically be the same as #265. I can write up a PR shortly.

**Comment by cassidyjames** [comment]
@TingPing not in the short term. But I wouldn't rule it out.
