### ISSUE TITLE
"THE BEST WAY TO GET APPS ON LINUX"

### ISSUE THREAD

**Issue by davidak** [flatpak/flatpak.github.io#267]
Nice claim, but why do you think exactly that it is the case?

Please add details and compare to similar tools like AppImage, Snappy and Docker.

It should be written for users and programmers.

When you know WHY it is exactly **the best way,** you might come up with a better claim.

Content can be on main page, about page (https://github.com/flatpak/flatpak.github.io/issues/254) and FAQ.

**Comment by allanday** [comment]
I agree that it would be good to have more details about the advantages of Flatpak; I think that's covered by #254.

However, a comparison with alternative technologies feels like too much information, and is tricky for various reasons - it's a lot of information to gather, process and keep up to date, and it's hard to do objectively. I'm pretty sure if we added such a thing, people would take issue with it.
