### ISSUE TITLE
browser web for flatpak

### ISSUE THREAD

**Issue by candrapersada** [flatpak/flatpak.github.io#268]
add browser brave, firefox, or chromium for flatpak

**Comment by allanday** [comment]
Thanks for the issue; I assume that this is requesting these apps to be available through Flatpak. Work on Firefox is ongoing (you can try it here - https://firefox-flatpak.mojefedora.cz/ ). I'm not aware of Brave or Chromium being available.

Note that this repository is for the flatpak.org website; it isn't used to track app requests.
