### ISSUE TITLE
How to install .flatpakref files via gui?

### ISSUE THREAD

**Issue by candrapersada** [flatpak/flatpak.github.io#269]
how install .flatpakref files via gui, the same as .deb files via GDebi for Linux Mint.

**Comment by TingPing** [comment]
GNOME-Software or Plasma Discover.

**Comment by candrapersada** [comment]
for opensuse and solus

**Comment by TingPing** [comment]
OpenSUSE certainly has GNOME-Software or Plasma Discover. Solus does not have a graphical flatpak handler *yet*.

**Comment by candrapersada** [comment]
add app version information for GNOME-Software and Plasma Discover

**Comment by candrapersada** [comment]
How to disable app auto update and How to manual app update

**Comment by TingPing** [comment]
Nothing does auto update yet.

**Comment by matthiasclasen** [comment]
gnome-software 3.30 does autoupate by default for flatpaks.
