### ISSUE TITLE
404 page is missing styling

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#273]
It looks like this:

![screenshot-2018-5-16 flatpak -- page not found](https://user-images.githubusercontent.com/213068/40112930-96f7db3a-58ff-11e8-9a28-54bc685ec8ac.png)

**Comment by jimmac** [comment]
I can't reproduce this. Works here.

**Comment by allanday** [comment]
Maybe my new exciting networking setup at home, then. :)
