### ISSUE TITLE
Gnome-Boxes flatpak does not install on gnome 3.22

### ISSUE THREAD

**Issue by prettydesk** [flatpak/flatpak.github.io#278]
using gnome-software or using command line, unable to install gnome boxes. 
as comparison, gnome-boxes install just fine on endless OS. 

reproduce error  on gnome 3.22 - Debian 9.4 and possibly later versionsof gnome:

 flatpak install flathub org.gnome.Boxes 
Updating: org.gnome.Platform/x86_64/3.28 from flathub
No updates.
Updating: org.freedesktop.Platform.ffmpeg/x86_64/1.6 from flathub
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.28 from flathub
No updates.
Installing: org.gnome.Boxes/x86_64/stable from flathub

1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds           
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: Failed to read commit 394af0191745ad1e55f81937b3d3e43224b489f577de058c4d7ba0d97c3bb6c1: No such metadata object 93f7ab47a54811c2babce257792a62f7e68ee23876ac4c7db7dae8ca7858c9ed.dirtree

Not certain if issue is relating to the gnome-boxes flatpak  or on flatpak itself since it now installs just fine on endless.

**Comment by AsciiWolf** [comment]
This should be reported [here](https://github.com/flathub/org.gnome.Boxes/issues).

**Comment by allanday** [comment]
For what it's worth, I asked about this issue on #flatpak and this is the response I got:

    that means they have a broken flatpak installation
    like, there is a file missing in the flatpak ostree repo

**Comment by matthiasclasen** [comment]
Hope flatpak repair worked
