### ISSUE TITLE
unable to install flatpak in ubuntu 14.04

### ISSUE THREAD

**Issue by chalan51** [flatpak/flatpak.github.io#287]
Uups, I cannot install flatpak on ubuntu 14.04, after
1- sudo add-apt-repository ppa:alexlarsson/flatpak
2- sudo apt update
3- sudo apt install flatpak
I receive the error
E: can not be able to locate flatpak package
(E: No se ha podido localizar el paquete flatpak)
Please direct me to some support regarding this issue
Thanks

**Comment by linkmauve** [comment]
You can close this issue, Ubuntu 14.04 hasn’t been supported by its upstream for more than one year already, and users should be advised not to run it anymore.
