### ISSUE TITLE
Inaccuracies in developer page diagram

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#29]
I love the idea of visually communicating the way Flatpak works and the current graphic looks great. There are a few issues I see with it though:

 * Runtimes are available inside the sandbox, but they are portrayed as being outside.
 * The animated lines represent very different things - the build process, calling a library at runtime, and IPC between app and operating system. However, they look equivalent, and to my eyes all look like IPC.
 * The graphic doesn't represent the way that runtimes depend on operating systems, and apps depend on runtimes.
 * It would be nice if the graphic could communicate that runtimes (and SDKs) contain libraries.
 * The operating system block uses a GNOME logo; this might be confusing to a lot of people.

How some of these issues could be addressed:

![flatpak-diagram](https://cloud.githubusercontent.com/assets/213068/15534434/af55c16a-2260-11e6-8cc3-0e541ff4fd58.png)

**Comment by jimmac** [comment]
commited a fix in 6a759c66722188061d241639bec52b8553444ea6
