### ISSUE TITLE
Incorporate the Flatpak intro video

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#290]
A [Flatpak intro video is being worked](https://github.com/flatpak/flatpak/issues/1892) on to coincide with the 1.0 release. When it's done, we ought to have it on flatpak.org.

My suggestion would be to put it on the home page, like this:

![flatpak org-aug-2018](https://user-images.githubusercontent.com/213068/44094055-06621c1a-9fcd-11e8-8b3b-296fdef151ff.png)

**Comment by bastianilso** [comment]
@allanday I have published the video now per @alexlarsson's request.
https://youtu.be/jDVCITRWGgs
