### ISSUE TITLE
"Fork me on GitHub" ribbon?

### ISSUE THREAD

**Issue by palasso** [flatpak/flatpak.github.io#3]
Since most of the development workflow is going to happen on github maybe it'd be nice to put a "Fork me on GitHub" ribbon.

While the "Get Involved" section is good, the ribbon is small, catchy and gets the message out that flatpak is FLOSS, has a github repo and uses github issues and that third-party contributors are welcome to improve it primarily using the github infrastructure.

Some websites that have ribbons:
https://github.com/blog/273-github-ribbons
https://simonwhitaker.github.io/github-fork-ribbon-css/
http://blog.dfilimonov.com/github-ribbons-css/
https://codepo8.github.io/css-fork-on-github-ribbon/

**Comment by jimmac** [comment]
Thanks for the suggestion, but it feels very invasive and perhaps something for a tiny project. I'm afraid I'm not slapping a cheesy ribbon on top of the site.
