### ISSUE TITLE
Font color wxformbuilder

### ISSUE THREAD

**Issue by damufo** [flatpak/flatpak.github.io#300]
Debian Stretch
XFCE 4.12
Font color white is difficult to see
How I can customize this?

![captura de pantalla_2018-10-24_22-42-47](https://user-images.githubusercontent.com/4057369/47460302-6dd22400-d7de-11e8-9dfa-3f4e13321474.png)
The font is thinner and larger in the SO execution that in the flatpak execution.
![captura de pantalla_2018-10-24_22-46-46](https://user-images.githubusercontent.com/4057369/47460546-08cafe00-d7df-11e8-9495-e0bc3e2293ae.png)

**Comment by jhasse** [comment]
This is a bug in wxWidgets 3.1.0 and has been fixed. Issue can be closed :)
