### ISSUE TITLE
Do not recommand restarting the system if it is not needed

### ISSUE THREAD

**Issue by probonopd** [flatpak/flatpak.github.io#303]
https://flatpak.org/setup/Ubuntu/ says

>4. Restart
>
>To complete setup, restart your system. 

Actually a restart may not be necessary, logging out of the desktop and logging in again may be [sufficient](https://github.com/flatpak/flatpak/issues/17#issuecomment-445044576).

(Why is this even needed?)

**Comment by TingPing** [comment]
> (Why is this even needed?)

It adds to `$XDG_DATA_DIRS` for desktop files to be picked up. This should probably be explained.

**Comment by probonopd** [comment]
If it would use `$HOME/.local/share/` then the log out and log in would not be needed?

**Comment by TingPing** [comment]
It wouldn't but a core design of Flatpak is to never conflict with files provided elsewhere.

**Comment by probonopd** [comment]
You are pointing out a deficiency of the current XDG desktop spec - it seems to assume that each application is available on the system in one version only. In AppImage, we are using an ugly workaround by using names such as `/home/me/.local/share/applications/appimagekit_2cbea0c6c0e442620923ecddcaa1e87f-xchat.desktop` in order to prevent collisions. Some goes for icon files and the like.

Would you like to collaborate on improving the XDG specs? ([More on this topic](https://github.com/AppImage/appimaged/issues/30))

**Comment by TingPing** [comment]
I can't speak for Flatpak but I believe such an invasive redesign of how applications work isn't the current goal.

**Comment by matthiasclasen** [comment]
Reinventing the world to solve corner cases is going to be an uphiill battle.

And it will never work for all the distros that flatpak is targeting.

**Comment by probonopd** [comment]
This was closed. Does this mean that it is no longer recommended to restart the system?

**Comment by matthiasclasen** [comment]
No, I think we want to keep the instructions simple and obvious. No need to go into details of how things are implemented.

**Comment by probonopd** [comment]
Only that on Live ISOs this completely breaks.

**Comment by matthiasclasen** [comment]
True. But thats your special niche. We are not trying to provide setup instructions for live images.

**Comment by xandkar** [comment]
> No, I think we want to keep the instructions simple and obvious. No need to go into details of how things are implemented.
> 
> The simple and obvious way to restart a session is to restart the system.

Not true. It makes it unnecessarily mysterious to anyone that has used non-Windows for more than 5 minutes.

**Comment by probonopd** [comment]
> The simple and obvious way to restart a session is to restart the system.

For me, the simple and obvious way to restart a session is to log out and log in again.
Not?
