### ISSUE TITLE
Flatpak support for NixOS & installation instructions on flatpak.org/setup for NixOS?

### ISSUE THREAD

**Issue by Zig-03** [flatpak/flatpak.github.io#305]

**Comment by allanday** [comment]
We could add instructions. We'd need to know:

 1. The command to install flatpak
 2. Any commands necessary to get graphical app management working
 3. The best way to setup Flathub (command line or clicking on a flatpakrepo file)

**Comment by Zig-03** [comment]
@allanday 
With a fresh install of NixOS, by using these commands, I managed to install a few flatpaks without any issues:
`nix-env -iA nixos.flatpak`
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`


`flatpak install flathub org.librepcb.LibrePCB`
`flatpak install flathub org.gnucash.GnuCash`

**Comment by allanday** [comment]
>  `nix-env -iA nixos.flatpak`

Is sudo or root needed for this?

**Comment by Zig-03** [comment]
@allanday yes
