### ISSUE TITLE
add new image

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#310]
Here is a new seasonal image that was kindly contributed by Caroline Hendriksen

![flatpak-tree](https://user-images.githubusercontent.com/4834845/50325971-c14ab080-04b5-11e9-91a8-b6b5c87cf8f7.png)

[Flatpak-Tree.svg.gz](https://github.com/flatpak/flatpak.github.io/files/2701595/Flatpak-Tree.svg.gz)

Unfortunately, middleman won't install or work on this Fedora system, so I can't produce a tested PR :(

**Comment by alexlarsson** [comment]
I really really tried to get middleman to run... But it seems we need @jimmac for this.
