### ISSUE TITLE
No textcolor specified in CSS

### ISSUE THREAD

**Issue by tastytea** [flatpak/flatpak.github.io#317]
The CSS is broken. I suspect the background color is specified, the text color is not.
To reproduce, configure your browser to use white text on black
background as fallback.

![screenshot_2019-01-05t18 38 12](https://user-images.githubusercontent.com/3681516/50727300-e6276080-1110-11e9-92b1-f3442afb5df9.png)

**Comment by jimmac** [comment]
I was going to ask about the specific element you're refering to, but looking at the screenshot, you might be talking about flathub.org, not flatpak.org? Please file flathub bugs against flathub.org
