### ISSUE TITLE
Setup instructions broken for Ubuntu 18.10 (cosmic)

### ISSUE THREAD

**Issue by riyad** [flatpak/flatpak.github.io#319]
Adding [the PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak) fails to fetch package lists for Ubuntu 18.10 (`cosmic`):

```
# apt update
[...]
Err:18 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu cosmic Release      
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                       
E: The repository 'http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu cosmic Release' does not have a Release file.
[...] 
```

Possible solutions:
* recommend using the [default distro packages](https://packages.ubuntu.com/cosmic/flatpak) (as in #260)
* fix the PPA to also build packages for `cosmic` (and maybe even `disco` due in April :wink: )

**Comment by riyad** [comment]
It seems the symptoms went away with the release of flatpak 1.2. There's now a PPA repo for Ubuntu 18.10 and APT doesn't complain any more. But the underlying problem still exists: the instructions are broken for new releases of Ubuntu until the following release of flatpak.

I still think the following steps should be considered:
- default to the repo packages (i.e. produce no accidental breakages for current releases)
- advertise the PPA for older releases
- maybe advertise the PPA in general for "early access" to newer versions

**Comment by danyeaw** [comment]
This should now be fixed with the [latest page](https://flatpak.org/setup/Ubuntu/). I also submitted #329 which adds Disco Dingo to the installation instructions as well. I recommend closing this issue. :+1:

**Comment by riyad** [comment]
Awsome, thank you. :slightly_smiling_face:
