### ISSUE TITLE
Nav bar: change "users" and "developers" to "run" and "build"

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak.github.io#32]
andreasn   it still says "Users" and "Developers" in the top navigation, 
               even though it has better titles in the page
               "Running" and "Create an app" ?
               "How to run" maybe
    aday_      or "install an app" and "build an app" ?
               or even just "run" and "build" ?
               short is good here
    andreasn   yeah
               Run and Build are nice

**Comment by andreasn** [comment]
Sorry for being late on the ball here.
Anyway, Looks good to me.
