### ISSUE TITLE
Gentoo Quick Setup page shows installing  flathub w/o root

### ISSUE THREAD

**Issue by GrantEdwards** [flatpak/flatpak.github.io#322]
The web page at https://flatpak.org/setup/Gentoo/ shows the flatpak remote-add command being run
as a normal user.  When you do that, the flatpack utility seg-faults with no error message.

The remote-add command needs to be run as root.

**Comment by TingPing** [comment]
> When you do that, the flatpack utility seg-faults with no error message.

Report that against https://github.com/flatpak/flatpak

Ideally with version numbers and a backtrace.

**Comment by GrantEdwards** [comment]
So has the web page been fixed to show that the 'remote-add' command is run as root instead of  as a normal user?

**Comment by TingPing** [comment]
It will run fine without root if you have polkit properly configured. If you don't its not really a big deal it should just fail without permissions. So as I see it the main problem is just the crash you encountered.
