### ISSUE TITLE
Japanese language support 

### ISSUE THREAD

**Issue by krizalidzero** [flatpak/flatpak.github.io#323]
Hello.

I am using Ubuntu Mate  18.10 Cosmic (specifically, the Cupertino style view. Basically, GTK stuff).
I had an issue being unable to install apps with the default repository flatpak, but I fixed that by adding the ppa.

Now, the problem is that when I install flatpaks in my computer (which is set to Japanese), apps will open but the kana (Japanese characters) are not visible, they just show up as squares.
This problem does not happen with snap equivalents, or AppImage even.

elementary's code's menu shows in English, but the user interface is unusable.
![screenshot at 2019-02-20 17-08-15](https://user-images.githubusercontent.com/44400318/53076082-206a8700-3532-11e9-9d8b-2844bff1322d.png)

It does not seem to happen everywhere, for instance Brackets will show mostly fine (because it just shows up in English) but opening other things within the flatpak will break.

![image](https://user-images.githubusercontent.com/44400318/53076220-848d4b00-3532-11e9-8be6-94d982d072d7.png)

Please help.

**Comment by allanday** [comment]
Sorry to hear that you've had this problem with Flatpak, and I'm sorry for the slow response to your issue. Unfortunately this isn't the best place to report general issues with Flatpak - it's just for website issues. If you are still experiencing problems, you could try the #flatpak IRC channel or mailing list.
