### ISSUE TITLE
Steam and PulseAudio

### ISSUE THREAD

**Issue by BinaryAura** [flatpak/flatpak.github.io#327]
After installing steam through flathub.org, I attempted to install Oxygen Not Included (ONI). The game launches, but is unable to output any sound at all. I contacted Klei Entertainment about this. They said the game uses PulseAudio, but it seems that the game cannot access PulseAudio from flatpak's sandbox. Attached is the email correspondence between Klei Entertainment and myself. I installed Steam through flathub.org's repo and ONI via default install in Steam.
[klei.pdf](https://github.com/flatpak/flatpak.github.io/files/3009805/klei.pdf)

**Comment by TingPing** [comment]
This is the repo for the website. Please report it in the correct repo: https://github.com/flathub/com.valvesoftware.Steam
