### ISSUE TITLE
runescape flatpak updating issues

### ISSUE THREAD

**Issue by mrmanitech** [flatpak/flatpak.github.io#328]
[linux@a6 ~]$ flatpak update
Looking for updates…
Required runtime for com.jagex.RuneScape/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/18.08) found in remote flathub
Do you want to install it? [Y/n]: Y

        ID                                    Arch   Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform              x86_64 18.08  i  flathub 250.9 MB / 293.0 MB
 2. [✓] org.freedesktop.Platform.Locale       x86_64 18.08  i  flathub  17.1 kB / 315.9 MB
 3. [✓] org.freedesktop.Platform.html5-codecs x86_64 18.08  i  flathub   4.8 MB / 4.9 MB
 4. [✗] com.jagex.RuneScape                   x86_64 stable u  flathub  12.7 MB / 12.9 MB

Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb
Changes complete.
error: There were one or more errors

**Comment by allanday** [comment]
These issues are for reporting problems with the Flatpak website only. For help with installation problems, it is best to ask on a more general Flatpak channel, like the #flatpak IRC channel or mailing list.

Sorry we couldn't help you here!
