### ISSUE TITLE
Add Guix setup page

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/flatpak.github.io#333]
It'd be possible to add Guix in the setup page now with nothing to be done other than installing the package which should be
`guix install flatpak`

On their packages page, this is their version so it's appropriate to do so, I believe. Someone would need to test this most likely.
![image](https://user-images.githubusercontent.com/39467792/57115416-ddd8de00-6d1c-11e9-9bda-6ca160437892.png)

**Comment by asddsaz** [comment]
I'll see if I can figure out how to add the instructions and make a PR.

**Comment by AsciiWolf** [comment]
I have some [questions and requests](https://github.com/flatpak/flatpak.github.io/pull/337#discussion_r361867214) before the current PR is merged. Unfortunately, the original author of the PR does not seem to be active on GitHub anymore. I think the best would be if someone could make a new PR, based on the original one, with issues from my comment addressed. :-)

**Comment by ghost** [comment]
XDG portals are currently missing from Guix System: https://issues.guix.gnu.org/37289 This is a considerable blocker in my opinion.

**Comment by mwleeds** [comment]
> XDG portals are currently missing from Guix System: https://issues.guix.gnu.org/37289 This is a considerable blocker in my opinion.

This has been fixed according to https://issues.guix.gnu.org/37289#2

**Comment by razzeee** [comment]
We have had guix for some time now, this could be closed
