### ISSUE TITLE
Chrome OS installation guide has a mistake

### ISSUE THREAD

**Issue by falcet** [flatpak/flatpak.github.io#335]
It's a website issue.

There's a missed command at the step #4 of the website page: https://flatpak.org/setup/Chrome%20OS

This command won't run without "sudo" at the beginning.

**Comment by allanday** [comment]
I'm unfamiliar with Chrome OS. On Linux distros, `sudo` isn't required or `remote-add`. Can you confirm that this is a Chrome-OS-specific issue?

**Comment by falcet** [comment]
Yes.
Chrome OS runs lightweight Debian through the virtual machine called
"Crostini". This command won't run without "sudo", like many other commands
in terminal. I have no idea why, but that's how it works.


Best regards,
Dmitry Konoplev

**Comment by allanday** [comment]
Fixed in the source branch.
