### ISSUE TITLE
Dropbox startup and nautilus integration

### ISSUE THREAD

**Issue by gpapaioa** [flatpak/flatpak.github.io#336]
Hello. I am using Dropbox on Centos 7.6 (mid-level linux user). When I run it, I don't get Nautilus integration. Is it something that it's not supported? Plus which is the best way to make Dropbox run on startup? Thank you

**Comment by allanday** [comment]
This product is for the Flatpak website only. Issues about the Flatpak version of Dropbox can be reported [here](https://github.com/flathub/com.dropbox.Client/issues). Alternatively, general questions about using Flatpak can be asked on the #flatpak IRC channel or mailing list. Thanks!
