### ISSUE TITLE
ssl cert error for docs.flatpak.org

### ISSUE THREAD

**Issue by jugmac00** [flatpak/flatpak.github.io#338]
https://docs.flatpak.org/en/latest/using-flatpak.html

see attached screen

![Screenshot from 2019-05-19 16-31-55](https://user-images.githubusercontent.com/9895620/57983594-264e0680-7a54-11e9-90f4-0a88d6fab73e.png)

**Comment by TingPing** [comment]
Wrong repo but its already reported.

**Comment by jugmac00** [comment]
Hi @TingPing  - could you give me a hint what the correct location to report this isse would be? Maybe even the link to the issue?
Thank you!

**Comment by TingPing** [comment]
https://github.com/flatpak/flatpak-docs/issues/133
