### ISSUE TITLE
Add Zorin OS page to Quick Setup

### ISSUE THREAD

**Issue by thomasstevenson** [flatpak/flatpak.github.io#345]
Zorin OS recently released a new version which includes both Flatpak (the latest version 1.4) as well as the Gnome Software Flatpak plugin by default, no additional setup needed. I've tested installing the Flathub repository file (flathub.flatpakrepo) from the Quick Setup page for Fedora and it works perfectly in Zorin OS.

Adding the Zorin OS page should be as simple as copying the Fedora page and changing the logo (which can be downloaded from this page on their site: https://zorinos.com/press)

**Comment by ArtyomZorin** [comment]
Added in  #381
