### ISSUE TITLE
Mendeley install 

### ISSUE THREAD

**Issue by 10stars19** [flatpak/flatpak.github.io#348]
following instructions for Mendeley produces the following error. 

Have I missed something? I have followed the setup instructions and restarted.

pi@raspberrypi:~ $ flatpak install flathub com.elsevier.MendeleyDesktop

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: Nothing matches com.elsevier.MendeleyDesktop in remote flathub

**Comment by barthalion** [comment]
Mendeley supports only x86_64.
