### ISSUE TITLE
Install doc - advise Ubuntu repo version way behind?

### ISSUE THREAD

**Issue by twtonicr** [flatpak/flatpak.github.io#349]
The advice here:
https://flatpak.org/setup/Ubuntu/

Like many people I have a general aversion to just adding repos on blind faith. 

So I found on 18.04, that  `sudo apt install flatpak` worked without adding the repo.  I was busy, so I just pressed on with using it.
Later I discovered that I had Flatpak 1.0.8 as a result, latest being Flatpak 1.4.2

The advice on the install page, though logically true, is a bit too literal to be helpful.  Could I suggest:
"With older Ubuntu versions, the official Flatpak PPA is the recommended way to install Flatpak **as distribution repos might not have the latest version**. To install it, run the following in a terminal:"

Adding repos is a risky thing and it's better to encourage confidence rather that expect people to go on blind faith. Knowing that I will not get the latest version from an official source is well worth underlining, and as I prefer instructions to explain why, rather than just give orders, especially as the linux world's docs are rarely error-free.

Also with no disrespect to Mr Larsson, an "Official" repo with some guy's name in the title doesn't really inspire confidence in its officialness.

**Comment by twtonicr** [comment]
It would seem sensible to me, as an exercise to persuade people to consider flatpak instead of apt, that in the 18.04 Long Term Service, it would be prudent to maintain the latest version of flatpak in the 18.04 repo.  Not just the 19.04, because many of us only ever run the LTS, especially for business. 

Just a thought.

**Comment by freechelmi** [comment]
So is the 1.08 OK to use ?

**Comment by barthalion** [comment]
*The guy's name* as you put it is the founder and main developer of the project. All PPA builds happen on Launchpad and packages are signed so I'm not sure why you worry about repository name that much.

It's not possible to land major version change in LTS releases. Ubuntu LTS receive only bugfix updates.

**Comment by twtonicr** [comment]
@freechelmi version 1.08 is way behind.  OK to use = unknown, but certainly won't have latest updates.

Only way to get up to date is follow the fanboi advice.

**Comment by freechelmi** [comment]
@abssorb : please don't be unrespectfull to others when you don't understand technology.

that is the way LTS works, and I also try to avoid PPA usually but that's the right way to go for LTS

**Comment by twtonicr** [comment]
The point is about communications, not technology.    As I said in the OP, there is no disrespect. 

People who are stuck iside the apt world are seeking a way out. They choose flatpak. As a result of a gap in communications (which it is in this community's power to improve) they will have a sub-optimal experience, and be none the wiser.   

All I'm saying is make a small change to the docs, and I put some effort into making a recommendation.

The reaction has been highly over-sensitive.  Hopefully people who land here from google will find what they need.

Good luck otherwise.

**Comment by AsciiWolf** [comment]
@freechelmi This is not accurate. As far as I know, packages in the main repository can (and in many cases do) get feature updates (if they don't break other stuff); packages in the universe repository can get feature updates as well, but only if a community volunteer prepares (and sends as a stable release update) them.
