### ISSUE TITLE
"flatpak run" alternative to run commands natively from shell?

### ISSUE THREAD

**Issue by twtonicr** [flatpak/flatpak.github.io#350]
I have a number of scripts which interact with apps installed on ubuntu 18.04.  E.g. apps gimp and spotify.

I'm trying to use flatpak versions of the apps instead, but they are "hidden" behind the flatpak run command, and changing all the scripts to use flatpak commands is too much of a side-quest.

Is there a way documented anywhere that via symlinks or some method, I can set up flatpak to integrate better?

gimp 
Found installed ref ‘app/org.gimp.GIMP/x86_64/stable’

spotify
Found installed ref ‘app/com.spotify.Client/x86_64/stable’

**Comment by allanday** [comment]
This project is for the flatpak.org website. For support questions, you'd be better off using the flatpak IRC channel or mailing list. See https://flatpak.org/about/

Good luck!
