### ISSUE TITLE
problem install software

### ISSUE THREAD

**Issue by junglaCODE** [flatpak/flatpak.github.io#351]
`Looking for updates…
error: org.gnome.Recipes not installed
[monolinux@deadpool flatpak]$ flatpak install flathub org.gnome.Games
Looking for matches…
Required runtime for org.gnome.Games/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.34) found in remote flathub
Do you want to install it? [Y/n]: y

org.gnome.Games permissions:
    ipc                  network      pulseaudio      wayland      x11      devices      dri      file access [1]
    dbus access [2]

    [1] host:ro, ~/.var/app/com.valvesoftware.Steam:ro
    [2] org.freedesktop.Flatpak, org.freedesktop.Tracker1

        ID                                            Arch            Branch          Op          Remote           Descarga
 1. [✗] org.gnome.Platform                            x86_64          3.34            i           flathub              3.3 kB / 318.3 MB
 2. [ ] org.gnome.Platform.Locale                     x86_64          3.34            i           flathub          < 322.7 MB (partial)
 3. [ ] org.freedesktop.Platform.GL.default           x86_64          19.08           u           flathub           < 40.7 MB
 4. [ ] org.freedesktop.Platform.VAAPI.Intel          x86_64          19.08           u           flathub            < 8.7 MB
 5. [ ] org.gnome.Games                               x86_64          stable          i           flathub            < 6.9 MB
 6. [ ] org.gnome.Games.Locale                        x86_64          stable          i           flathub            < 1.2 MB (partial)

Error: opendir(refs/remotes): No such file or directory
error: Failed to instalar org.gnome.Platform: opendir(refs/remotes): No such file or directory
`

**Comment by felipeborges** [comment]
What's is your `flatpak --version`?

**Comment by barthalion** [comment]
Please report it at https://github.com/flatpak/flatpak
