### ISSUE TITLE
Some Fedora users might not be running GNOME/KDE

### ISSUE THREAD

**Issue by felipeborges** [flatpak/flatpak.github.io#352]
On the [Fedora quick setup page](https://flatpak.org/setup/Fedora/) there is only a download link to a .flatpakrepo file. This is useful when the user has GNOME Software or KDE Discover, but some users are using other desktop environments with software store apps that still don't support Flatpak or DEs that don't have a software store app at all.

It would be nice IMO to have command line instructions too, in a section below.

**Comment by alexlarsson** [comment]
Makes sense to me to mention the fallback if this is not working.
