### ISSUE TITLE
Fix the cert on docs.flatpak.org and enable HTTPS

### ISSUE THREAD

**Issue by andreldmonteiro** [flatpak/flatpak.github.io#358]
Before enabling HTTPS the certificate of docs.flatpak.org needs to be fixed, it currently isn't valid for the domain, after that enable HTTPS.

**Comment by mwleeds** [comment]
This is done, and also the repo for docs.flatpak.org is https://github.com/flatpak/flatpak-docs

**Comment by barthalion** [comment]
Correct, we fixed it in December.
