### ISSUE TITLE
Cannot download flatpak apps

### ISSUE THREAD

**Issue by qpackard** [flatpak/flatpak.github.io#359]
I believe I have successfully installed Flatpak 1.4.3 on my Ubuntu 19.10, yet when I go to the App Outlet and try to download an app I get this message every time:
"Occurred an error 
Looks like you not configure support to Flatpak packages. Please, verify your setup." [sic]
Have I missed something? Is this the correct forum for my question?

**Comment by mwleeds** [comment]
The correct forum for such a question is https://github.com/flatpak/flatpak

It would also be helpful if you said what steps you followed to install Flatpak.
