### ISSUE TITLE
bwrap: execvp openaudible: No such file or directory

### ISSUE THREAD

**Issue by minnixtx** [flatpak/flatpak.github.io#364]
OS: Mint 19.3
Platform: org.freedesktop.Platform 19.08
SDK: org.freedesktop.Sdk 19.08
flatpak version: 1.0.9-0ubuntu0.1
flatpak-builder version: 0.10.9-1ubuntu1

Following this [guide](https://github.com/flatpak/flatpak.github.io/blob/81bb006fd96b9a13170bd876316eb5a4eb48244b/source/bundling-a-java-app.html.haml.markdown) for flatpak-builder for java applications I get

`bwrap: execvp openaudible: No such file or directory`

When `flatpak run org.openaudible.App`

It doesn't show up in my applications menu either.

I'm trying to build [openaudible](https://openaudible.org/).

My .json file

`{
    "app-id": "org.openaudible.App",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "19.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "openaudible",
    "finish-args": [
        "--persist=.java",
        "--share=ipc", "--socket=x11",
        "--share=network"
    ],
    "modules": [
        {
            "name": "openaudible",
            "no-autogen": true,
            "sources" : [
                {
                    "type": "archive",
                    "url": "https://github.com/openaudible/openaudible/archive/v1.6.5.tar.gz",
                    "sha256": "7cee6dd7d07179fd52851d15e592ca1474a668078d191410d2b090e45c1cb9cc"
                },
                {
                    "type": "file",
                    "path": "openaudible-Makefile",
                    "dest-filename": "Makefile"
                }
            ]
        }
    ]
  }`

My Makefile:

`all:
	true
install:
	mkdir -p /app/openaudible /app/bin
	cp -ra * /app/openaudible
	ln -s /app/openaudible/openaudible /app/bin`

**Comment by mwleeds** [comment]
That tutorial was removed in 2017 (b7e3ac65c2ba75bc3ce8587334a66a6dcc5dc846)
