### ISSUE TITLE
Update Ubuntu setup page

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/flatpak.github.io#365]
Since the latest release (20.04), the Flatpak package was moved to the universe repo. The instructions to install Flatpak on Ubuntu needs to be updated to mention that.

**Comment by AsciiWolf** [comment]
There are also changes regarding GNOME Software that is now [distributed using Snap](https://www.omgubuntu.co.uk/2020/02/ubuntu-snap-store-transition) in Ubuntu since 20.04 without a Flatpak plugin available to install (for now). So, sadly, graphical installation of Flatpaks probably won't be possible in Ubuntu anymore.

**Comment by hellpe** [comment]
> So, sadly, graphical installation of Flatpaks probably won't be possible in Ubuntu anymore.

I've done a quick test on a virtualized 20.04 install, and by following the instructions on the Flatpak website, you can still manage flatpaks graphically on Ubuntu. The thing is, installing 'gnome-software-plugin-flatpak' pulls 'gnome-software' as a dependency, which leads to this awkward situation where two very similar but different "app stores" are installed on the same machine:

![Capture d’écran depuis 2020-04-25 15-32-56](https://user-images.githubusercontent.com/1238320/80281264-3c575300-870a-11ea-9411-b7b841099717.png)

**Comment by AsciiWolf** [comment]
[Related issue](https://bugs.launchpad.net/snap-store/+bug/1871944).

**Comment by kenvandine** [comment]
> Since the latest release (20.04), the Flatpak package was moved to the universe repo. The instructions to install Flatpak on Ubuntu needs to be updated to mention that.

Flatpak has always been a universe package.  And actually the process to add flatpak support on Ubuntu as document are the same.  All you have to do is install gnome-software-plugin-flatpak either via the command line or via the snap-store GUI. 

I do think the Yaru icon for org.gnome.Software looks too similar to the ubuntusoftware icon.

**Comment by mwleeds** [comment]
Since 86b9989c0207ae0a34d345d86216daef9029eff5 we have a note about the two software centers.
