### ISSUE TITLE
Add Manjaro Quick Setup page

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak.github.io#370]
[Manjaro](https://manjaro.org) gained a pretty big user base in last years. It would be great to have a Quick Setup page for this popular distro.

**Comment by AsciiWolf** [comment]
Manjaro should now [have](https://www.gamingonlinux.com/articles/manjaro-needs-testers-for-the-upcoming-manjaro-gnome-200-release-snap-and-flatpak-support-ootb.16468) out-of-box Flatpak support, including graphical installation!

**Comment by AsciiWolf** [comment]
Manjaro 20 was recently released with out-of-box Flatpak support, including the Flathub repo. However, to be able to install Flatpaks using GUI, users have to enable it first in the Software Center (pamac-gtk) settings:

![pamac_flatpak](https://user-images.githubusercontent.com/2339930/80382969-43fe2f80-88a3-11ea-83da-db2c6d3311f4.png)

**Comment by svastian99** [comment]
Here are the instructions to install Flatpak in Manjaro:
https://wiki.manjaro.org/index.php?title=Flatpak#Installing_Flatpak

**Comment by haggen88** [comment]
Manjaro KDE 20.0.3

![manjaro full](https://user-images.githubusercontent.com/68134588/87969537-56e26380-ca90-11ea-9c2a-51d32282eb51.png)

The instructions to install Flatpak on Manjaro should be something like: 

Open the Pacman package manager [look in the Menu: "Add / Remove Software"], click on the triple line menu [or dots depending on the Desktop Environment] on the right, in the drop down menu select "Preferences", navigate to the tab " Flatpak "and slide the control to Enable Flatpak support [it is also possible to enable checking for updates]. The installation of the Flathub repository is automatic.  Now you just need to exit and restart the system.

--

Manjaro SVG logo: 
[Manjaro 128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5031448/Manjaro.128px.svg.zip)

**Comment by dreaddr** [comment]
Why is this still not added? Manjaro supports flatpaks out of the box so mentioning how to enable them in the quick setup page should be rather obvious since its a very popular distro now.

**Comment by AsciiWolf** [comment]
I am unfortunately too busy with other tasks, feel free to send a PR. :-)

**Comment by dreaddr** [comment]
@haggen88 I used the instructions you provided in this issue

**Comment by AsciiWolf** [comment]
#464
