### ISSUE TITLE
Plugins icons and other stuff

### ISSUE THREAD

**Issue by caarlosfuentes** [flatpak/flatpak.github.io#373]
Hi, i have installed by Flatpak gimp2.10 in my Ubuntu 18-04, generally if i want install a plugin, i download the plugin and put into the folder plugins, but it doesn't work. I mean i go to the path in /home/myuser/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins, put the plugin, i open gimp then not plugin. maybe there is something i do wrong, can help me please

**Comment by AsciiWolf** [comment]
Hi, this is not a correct place to report your issue. This tracker is for the Flatpak.org website issues. If you installed GIMP from Flathub, you can report the issue [here](https://github.com/flathub/org.gimp.GIMP/issues).
