### ISSUE TITLE
Add --user option to Fedora setup guide

### ISSUE THREAD

**Issue by pcf86** [flatpak/flatpak.github.io#379]
The command provided in the [Fedora setup guide section](https://flatpak.org/setup/Fedora/) doesn't work, as it needs to have the additional `--user` option.

**Comment by mwleeds** [comment]
Can you explain what doesn't work when the system installation is used?

**Comment by pcf86** [comment]
Please disregard. I tried to reproduce the issue and it prompted for a password (probably I didn't see the prompt window the first time and it probably failed the setup).
It works fine now, without the `--user` option.
