### ISSUE TITLE
Add KaOS to Quick Setup

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#388]
KaOS a rolling release distribution also has Flatpak in its [repositories](https://kaosx.us/packages/packages.php?sortby=&sortdir=&flagged=&page=&repo=&exact=&search=flatpak). 

[Here](https://kaosx.us/docs/flatpak/) are the official instructions to install it.  Basically:

- Install Flatpak
To install Flatpak onKaOS, run the following in a terminal:
$ sudo pacman -S flatpak

- Add the Flathub repository:
Flathub is the best place to get Flatpak apps. To enable it, run:
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- Restart
To complete setup, restart your system. Now all you have to do is install some apps.

---
Note:  Since version [2017.06](https://kaosx.us/news/2017/kaos06/) Discover is added as the GUI for Flatpak.   Discover is not installed by default, it can be installed by running: 
> sudo pacman -S discover

The installation of the Flatpak backend as the Flathub repositor configuration is automatic.

[KaOS 2020.07]
![KaOS](https://user-images.githubusercontent.com/68134588/89644220-fa13e500-d8a6-11ea-830e-ce0a1916ec19.png)

svg logo: 
[_kaos_logo 128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5040532/_kaos_logo.128px.svg.zip)

**Comment by ShalokShalom** [comment]
Like to mention, that KaOS is a completely self-packaging and independent distribution, so no other distro provides packages for it, considering this [new issue](https://github.com/flatpak/flatpak.github.io/issues/471)
