### ISSUE TITLE
Add PCLinuxOS to Quick Setup

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#392]
For the installation of Flatpak in [PCLinuxOS](http://pclinuxoshelp.com/index.php/Installing_Software#Using_Flatpak)  you simply have to:

- Install the Flatpak package from Synaptic
 
- Add the Flathub repository:
>sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- It is suggested to reboot the system

![pclnx](https://user-images.githubusercontent.com/68134588/90321445-3eebeb80-df39-11ea-9386-f729f3784f05.png)

svg logo: 
[PCLinuxOS.128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5031305/PCLinuxOS.128px.svg.zip)

**Comment by AsciiWolf** [comment]
Is graphical installation of Flatpaks also supported?

**Comment by haggen88** [comment]
By default PCLinuxOS [manages](https://pclinuxoshelp.com/index.php/Installing_Software#Using_Synaptic_Package_Manager) the software installation using [Synaptic](http://pclinuxoshelp.com/index.php/Frequently_Asked_Questions), doesn't bring something like an AppStore/Software Center [there is no Discover or Gnome Software in the repositories].


>The recommended way of installing additional software is to install from the official PCLinuxOS repository. This has the advantage that the software has been built and tested to be compatible with PCLinuxOS and also will ensure that any additional packages (dependencies) required by the software will automatically be installed. The easiest way is to use Synaptic Package Manager which is the graphical application used to manage software on PCLinuxOS. The Synaptic and the Repositories page gives an overview of how to use Synaptic and specifically search for software to install. 

--

> Can I install software from outside the software repository?

>Installing packages from outside sources is discouraged and not supported because it can lead to problems with the rolling release updates. If you can find an RPM package for the software then it might install successfully if it has no dependencies or its dependencies can be satisfied by packages in the repo. Even then you may find that future Synaptic updates will want to remove it or will fail with packages being held back.

>Where possible it would be best to try to use AppImages or Flatpak images (flatpak is available in the repo) or compile the software yourself to run from your home directory so it doesn't interfere with system updates.
