### ISSUE TITLE
Add Ubuntu Studio to Quick Setup

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#404]
Ubuntu Studio allows the use of flatpak following the same instructions as Ubuntu.
Ubuntu Studio 20.04 has Gnome-Software as its app store  but it comes without the Flatpak plugin.
It can be activated manually [In the Installed section, search for Software and select Flatpak Support].

![ubuntu studio1](https://user-images.githubusercontent.com/68134588/89249428-23e7b600-d5e0-11ea-8fb9-9901137c7b8e.png)

![ubuntu studio2](https://user-images.githubusercontent.com/68134588/89249444-2b0ec400-d5e0-11ea-9aaa-4c9a9ffda0c1.png)

svg logo: 
[Ubuntu Studio 128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5019926/Ubuntu.Studio.128px.svg.zip)

**Comment by AsciiWolf** [comment]
Ubuntu Studio 20.04 does not use Snap version of GNOME Software by default?

**Comment by haggen88** [comment]
edit [corrected]> 
@AsciiWolf  The Gnome-software version is 3.36.1 from the Ubuntu repositories. Does not bring the SnapStore/Ubuntu Software [gnome-software modified to **only** use .deb and snap ] by default. From what I have seen it is only used by Ubuntu.  All [official](https://snapcraft.io/docs/installing-snapd) Ubuntu flavor bring Snap pre-installed.

**Comment by eeickmeyer** [comment]
Ubuntu Studio Leader here. This gets my blessing.
