### ISSUE TITLE
Outdated copy of website at flatpak.github.io

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak.github.io#406]
The website at https://flatpak.org is up to date with this repo, but the website at https://flatpak.github.io has old content and should be taken down.

**Comment by mwleeds** [comment]
I think the cause might be that there are still active GitHub Pages deployments on the https://github.com/flatpak/flatpak repo even though the `gh-pages` branch was archived, but I don't have permission to do anything about it.

**Comment by barthalion** [comment]
Took a while but figured out how to remove it and it's gone now.
