### ISSUE TITLE
[Bug] The Deepin logo is not displayed on the Quick Setup page

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#407]
I don't know if it's a file or web problem but it doesn't appear:

![deep](https://user-images.githubusercontent.com/68134588/89370070-d6397f00-d6ad-11ea-831f-7cf87aadc784.png)

Here's another [source](https://github.com/linuxdeepin/deepin-icon-theme/commit/10f55c042b0c038187ab75abdc24190f7cd31cc4) of the svg logo: 
[Deepin.128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5031101/Deepin.128px.svg.zip)

**Comment by mwleeds** [comment]
My mistake, fixed in 8708933a8cea48d2e6ab3298e4b5fd655677f5fd

**Comment by haggen88** [comment]
> My mistake, fixed in [8708933](https://github.com/flatpak/flatpak.github.io/commit/8708933a8cea48d2e6ab3298e4b5fd655677f5fd)

@mwleeds the logo does not appear yet
regards

**Comment by mwleeds** [comment]
I see the Deepin logo in Chrome but not Firefox which is pretty strange.

**Comment by mwleeds** [comment]
Never mind, it shows in both now.

**Comment by haggen88** [comment]
@mwleeds  Reviewing Quick Setup I realized that all logos have a blank margin to generate space between logos and allow the correct visualization of the zoom.   The image used for the Deepin logo does not have it so it looks bigger compared to the others.    If possible, could you update it ?: here is the corrected file: [ISO安装器-128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5113451/ISO.-128px.svg.zip)

Regards

**Comment by mwleeds** [comment]
@haggen88 done, thanks
