### ISSUE TITLE
Add Netrunner to Quick Setup

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#411]
Netrunner is a Debian Stable based distribution that allows the installation of Flatpak. Netrunner [20.01] allows you to install applications using Synaptic and Discover 5.14, which does not have the Flatpak backend integrated. 

The instructions are:

- Install Flatpak
To install Flatpak on Netrunner, run the following in a terminal:
$ sudo apt install flatpak

- Install the Discover Flatpak backend
The Flatpak plugin for the Software app makes it possible to install apps without needing the command line
To install  run:
$ sudo apt install plasma-discover-backend-flatpak

- Add the Flathub repository
Flathub is the best place to get Flatpak apps. To enable it, run:
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

After installing the backend, to achieve the activation of the Flatpak integrated support, just go to Settings> Flatpak> Set as default. 

- Restart
To complete setup, restart your system. Now all you have to do is install some apps.

---

![n1](https://user-images.githubusercontent.com/68134588/89624749-b4362d00-d864-11ea-8749-dfacf9300323.png)

![n2](https://user-images.githubusercontent.com/68134588/89624767-bac4a480-d864-11ea-94d3-8e2e6d9f1e2d.png)

svg logo:
[_netrunner 128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5040131/_netrunner.128px.svg.zip)

**Comment by mwleeds** [comment]
Just FYI these distros will get added more quickly if you submit them as PRs rather than issues, if you're able.
