### ISSUE TITLE
Add Flathub logo on Flatpak website

### ISSUE THREAD

**Issue by haggen88** [flatpak/flatpak.github.io#423]
The use of Flatpak grows within distributions, but I think it is also important to strengthen the link to the Flathub repository. I think it is a good idea that the links that redirect to Flathub on the Flatpak website could include its logo to facilitate the visual association of the repository.

[Here](https://trends.google.com/trends/explore?date=today%205-y&q=appimagehub,flathub,snapcraft) you can see the trends in the web search for different "appstore" of software related to the Flatpak niche.

**Comment by mwleeds** [comment]
Could you be more specific about which links you're talking about and where you think a logo should go?

**Comment by haggen88** [comment]
I mean where it says: "_Already set up? Head over to Flathub to install some apps_",    and maybe where it says "_Now all you have to do is install some apps!_" [at Quick Setup].

**Comment by mwleeds** [comment]
Would probably need input from a designer on where exactly to put the logo and if it's needed
