### ISSUE TITLE
Criteria for distro inclusion?

### ISSUE THREAD

**Issue by schance995** [flatpak/flatpak.github.io#442]
I couldn't find any guidelines for this so I want to ask:

1. What components of Flatpak have to work for a distro to be listed? For example xdg-portals should work (https://github.com/flatpak/flatpak.github.io/issues/333) but what about PulseAudio since Flatpak apps with audio playback do not work some distros?
2. Ubuntu has many of flavors, which means that eventually there would be a significant portion of the setup page dedicated to something-Ubuntu. To generalize this, is there such a thing as a "distro uniqueness" criteria?
3. Are there other factors to consider?

**Comment by mwleeds** [comment]
Let's centralize the discussion in #471
