### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [flatpak/flatpak.github.io#446]
I can do it if you want.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by mwleeds** [comment]
Feel free to make a PR (:

**Comment by razzeee** [comment]
@vitaly-zdanevich did you end up starting on this?

**Comment by vitaly-zdanevich** [comment]
No, currently I do nothing about it, I need an aproove.
