### ISSUE TITLE
Ubuntu instructions outdated

### ISSUE THREAD

**Issue by Eonfge** [flatpak/flatpak.github.io#450]
While maintaining Lollypop, I've run into the issue that multiple people are using the Ubuntu-included Flatpak binaries:
https://github.com/flathub/org.gnome.Lollypop/issues/123

This gives issues, since they are mostly outdated:
- 18.04: 1.0.9
- 20.04: 1.6.5
- 20.10: 1.8.2

For 20.04, the setup instructions need to be updated. Right now, 20.04 doesn't recommend the PPA from Larsson, but obviously 1.6.5 is no longer support.

For 20.10, downstream should be politely encouraged to deploy security updates. If failing to do so, it would be better to recommend the PPA for all Ubuntu versions, now and in the future.

**Comment by Eonfge** [comment]
@AsciiWolf I see that you authored the last pull request, but I'm not sure who is actually responsible for the website. You know who I sould mail about this?

**Comment by Eonfge** [comment]
Also, we must double check support for 20.10, because right now Groovy is unsupported: 
https://github.com/flatpak/flatpak/issues/4033

**Comment by AsciiWolf** [comment]
Feel free to send a PR. :-)

**Comment by Eonfge** [comment]
Web development. How hard can it be...

**Comment by Eonfge** [comment]
Well, there is the answer. I'll spend the rest of the evening cleaning out gems from /usr/share.

**Comment by AsciiWolf** [comment]
It is not a good idea to install them under root, I have already made the same mistake. :-) Anyway, I have hopefully finally fixed it by switching to mini_racer instead of therubyracer (#482). :-)
