### ISSUE TITLE
[Blog post] Response to flatkill.org

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/flatpak.github.io#454]
Hi,

There is a post spreading misinformation about Flatpak, and inciting fear in the Linux community. I initially did not want to mention it, but since it is at the top of Google, I think it should be addressed. More and more people are starting to believe the post on flatkill, and I think that it's important to have a response.

I wouldn't mind writing a response; I have watched many videos about Flatpak, from FOSDEM, to DevConf, and more, and I have read many documentation.

| 1 | 2 | 3 | 4
|---|---|---|---|
![image](https://user-images.githubusercontent.com/50847364/111252176-eec82b00-85e6-11eb-8057-4fbdff910f4a.png) | ![image](https://user-images.githubusercontent.com/50847364/111252208-f8519300-85e6-11eb-949a-e3e6f8156d67.png) | ![image](https://user-images.githubusercontent.com/50847364/111252220-03a4be80-85e7-11eb-879f-835bbfea5395.png) | ![image](https://user-images.githubusercontent.com/50847364/111252258-19b27f00-85e7-11eb-8565-df18d5e3f548.png)

**Comment by mwleeds** [comment]
There is a (perhaps a bit dated) response here: https://ramcq.net/2018/10/15/flatpak-sandbox-security/

**Comment by TheEvilSkeleton** [comment]
@mwleeds they deliver some great points! Although, I've never seen this article in news sites, or even in Reddit which is unfortunate.

Since it's from 2018, I think people will also disregard it.

I've written a direct response over a month ago. Is it possible for me to get the response to https://flatpak.org/blog-posts/ once I'm completely done writing the response, or are there some hard requirements?

My response is here: https://theevilskeleton.frama.io/2021/02/11/response-to-flatkill-org.html.

**Comment by mwleeds** [comment]
@TheEvilSkeleton looks high enough quality to be included on the blog posts page. Submit a PR when it's ready?

**Comment by TheEvilSkeleton** [comment]
@mwleeds do you have anything to suggest before I PR? If not, then I'll PR.

**Comment by RennyDemmy** [comment]
Good. Flatpak doesn't deserve the neither the hate, nor this hoax.

**Comment by mwleeds** [comment]
@TheEvilSkeleton as I said on IRC, I don't think it's accurate to say that GIMP/Inkscape/Audacity/VLC need full filesystem access and can't eventually be made to use portals.

**Comment by TheEvilSkeleton** [comment]
@mwleeds that's a fair point. Though I got to this conclusion from a GIMP developer https://github.com/flathub/org.gimp.GIMP/pull/74#issuecomment-716149065. I'm pretty sure the other developers would feel that way.

That said, I think it's a matter of time we will be able to use portals in all the programs. I'll PR soon.

**Comment by mwleeds** [comment]
Looks like the wording hasn't changed and is in my opinion misleading.

> Two of their examples, GIMP and Inkscape, are image and vector editors respectively. They also need additional permissions to work, e.g. to edit on an external drive, a USB stick, or even Git repositories to edit logos, etc. Audacity and VLC also need additional permissions to run on external devices.

That makes it sound like portals can't be used to access files on external drives. Based on the [comment](https://github.com/flathub/org.gimp.GIMP/pull/74#issuecomment-716149065) you linked to, the technical barriers to using portals more are more subtle than that.

**Comment by TheEvilSkeleton** [comment]
Ah, I see what you mean. I'll change it in a bit.

**Comment by TheEvilSkeleton** [comment]
> Another thing is that three of their examples, VSCodium, PyCharm, and Octave, are IDEs. It is crucial for an IDE to have access to home or host filesystems, for Git repositories, and for other external uses, otherwise it is not very useful. Two of their examples, GIMP and Inkscape, are image and vector editors respectively. They also need additional permissions to work, e.g. to edit on an external drive, a USB stick, or even Git repositories to edit logos, etc. Audacity and VLC also need additional permissions to run on external devices. **Needless to say, these applications will eventually support portals to prevent access to the home or host filesystems without losing functionality.**

Is this good?

**Comment by mwleeds** [comment]
How about this?
> Another thing is that three of their examples, VSCodium, PyCharm, and Octave, are IDEs. It is crucial for an IDE to have access to home or host filesystems, for Git repositories, and for other external uses, otherwise it is not very useful. Two of their examples, GIMP and Inkscape, are image and vector editors respectively. They also need additional permissions to work, since making them use portals for all host system file access is techincally [complicated](https://github.com/flathub/org.gimp.GIMP/pull/74#issuecomment-716149065). Audacity and VLC face similar barriers, but all these applications should eventually be able to use portals instead of direct home or host filesystem access without losing functionality.

**Comment by TheEvilSkeleton** [comment]
> techincally

I fixed the typo.

I think it's good to go now. https://theevilskeleton.frama.io/2021/02/11/response-to-flatkill-org.html

![image](https://user-images.githubusercontent.com/50847364/111711060-5669ba80-8821-11eb-88d8-9dc45d2da641.png)
