### ISSUE TITLE
The user interface is not adaptive

### ISSUE THREAD

**Issue by colaliu1** [flatpak/flatpak.github.io#458]
When I use the commands on that browser(https://flatpak.org/setup/Debian/),It doesn't work(flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo).It can be used before, but now it reminds me that the TLS handshake failed, resulting in no plug-in and adaptive scene interface on the user interface.

**Comment by mwleeds** [comment]
Sorry this doesn't make sense to me. If you want help with Flatpak, try the `#flatpak` IRC channel. If you think you found a bug in Flatpak, please report it [here](https://github.com/flatpak/flatpak). And if this is actually a bug about the Flatpak website for which this is the repository, please provide more information.
