### ISSUE TITLE
Prioritize GUI Workflow in Debian/Ubuntu Install Instructions 

### ISSUE THREAD

**Issue by indolering** [flatpak/flatpak.github.io#465]
I'm trying to improve the UX of Flatpak on Ubuntu.  One major improvement would be to use [AptURL](https://wiki.ubuntu.com/AptUrl) to install Flatpak `apt://flatpak,gnome-software-plugin-flatpak?section=universe` and a `flatpakref` link or `flatpakrepo` file to add the Flathub repo.  The CLI instructions would still be available underneath these links.

**Comment by AsciiWolf** [comment]
Unfortunately, because the Software app is distributed as a Snap since Ubuntu 20.04 and does not support graphical installation of Flatpak apps, installing gnome-software-plugin-flatpak will also install a deb version of Software and result in two Software apps being installed at the same time. This is not ideal and can be problematic.

**Comment by AsciiWolf** [comment]
You can [try asking](https://bugs.launchpad.net/snap-store-desktop) Canonical to add the Flatpak plugin to their [Software Snap](https://gitlab.gnome.org/Community/Ubuntu/gnome-software). I already tried asking some time ago, but they were not interested.

**Comment by indolering** [comment]
What about narrowing this request to switch to an AptURL for the Flatpak dependency only?  An independent GUI Flatpak manager/Flathub store or a PPA mirror might work, but that can come later.

**Comment by AsciiWolf** [comment]
Sorry, but I don't think that's a good idea. It was already discussed on another distro.

**Comment by indolering** [comment]
> Sorry, but I don't think that's a good idea. It was already discussed on another distro.

Link?

**Comment by AsciiWolf** [comment]
I don't remember anymore, but it was the same case - where only part of the process could be done using GUI.

**Comment by indolering** [comment]
Welp, reasonable people can disagree.
