### ISSUE TITLE
Wrong name for flatpak discover backend on Kubuntu Hirsute 21.04

### ISSUE THREAD

**Issue by mystiquewolf** [flatpak/flatpak.github.io#466]
On your site the package to install is named plasma-discover-flatpak-backend, but the real package is named plasma-discover-backend-flatpak in Ubuntu Hirsute 21.04 repositorites.

**Comment by AsciiWolf** [comment]
This was already fixed in #463, but the build failed: https://github.com/flatpak/flatpak.github.io/runs/2683305609

/cc @barthalion

**Comment by AsciiWolf** [comment]
#468
