### ISSUE TITLE
Could I add some file to flatpak app?

### ISSUE THREAD

**Issue by cathaysia** [flatpak/flatpak.github.io#467]
digikam lacks some libs about mysql driver, it cause this app not work for me. I had post this bug on KDE, but could I add some libs to flatpak to run it?

I find `/var/lib/flatpak/app/org.kde.digikam` store files, but it seem not work after I add mysql driver?

**Comment by AsciiWolf** [comment]
You should write this here: https://github.com/flathub/org.kde.digikam/issues/17
