### ISSUE TITLE
flatpak can't install Firefox 89.0

### ISSUE THREAD

**Issue by harderm1** [flatpak/flatpak.github.io#472]
I have Firefox vsn. 87.something on Linux Mint (latest vsn I think) and some Amazon Prime videos will no longer run on it.  So I am trying to install FF vsn 89 and failing at every attempt of every kind, including flatpak's facility.  It downloaads the .tar file and appears to complete the install, yet when I open FF, it is still running vsn 87.  How do I install this upgrade?

**Comment by AsciiWolf** [comment]
This repo is for a Flatpak.org website. You should report your issue [here](https://bugzilla.mozilla.org) instead.
