### ISSUE TITLE
Kubuntu instructions outdated

### ISSUE THREAD

**Issue by Zahrun** [flatpak/flatpak.github.io#473]
Hi,

The plasma-discover-flatpak-backend package is available from 18.04 to 20.10. It is dropped since 21.04.
The new name is plasma-discover-backend-flatpak (two last words reversed) and is available from 20.04 onward.

**Comment by AsciiWolf** [comment]
Hi,

thanks for your report. This was already fixed, however we currently have issues with the Flatpak website deployment, so the actual website was not updated yet.
