### ISSUE TITLE
[Kubuntu Quick Setup] command to install flatpak backend for plasma refers to wrong package name

### ISSUE THREAD

**Issue by andreaippo** [flatpak/flatpak.github.io#476]
https://www.flatpak.org/setup/Kubuntu/

Step 2 says:

sudo apt install plasma-discover-flatpak-backend

This package does not exist:
https://packages.ubuntu.com/search?suite=hirsute&section=all&arch=any&keywords=plasma-discover-flatpak-backend&searchon=names

Whereas plasma-discover-_backend-flatpak_ does:

https://packages.ubuntu.com/hirsute/plasma-discover-backend-flatpak

**Comment by AsciiWolf** [comment]
Thanks for your report. This was already fixed, however it is waiting for #468 to be resolved.

**Comment by andreaippo** [comment]
Hello @AsciiWolf , a user on Reddit just reported this very same issue again, and I think that a simple doc update shouldn't take this long or it may turn people away from using flatpak, especially less experienced users that won't understand there's a simple workaround.

Any chances to update the doc without waiting for #468 ? I'm on mobile and couldn't really find a way to inspect the contents of the changes for which the build is failing. If there's anything more than the change in the installation guide document, then maybe it would be wiser to decouple the fix and have it merged asap.

Thanks and regards,
Andrea.
