### ISSUE TITLE
Too many (1212) search results

### ISSUE THREAD

**Issue by ls-1N** [flatpak/flatpak.github.io#477]
I don't know what exactly is going wrong but I noticed a pattern which maybe points to some bug with the search.

## Expected 
When searching for[ `minutor`](https://flathub.org/apps/search/minutor) or [`lutris`](https://flathub.org/apps/search/lutris) I get 0-10 results roughly. Probably 0 since those package don't seem flatpakked yet.

## Actual
When searching for[ `minutor`](https://flathub.org/apps/search/minutor) or [`lutris`](https://flathub.org/apps/search/lutris) I get 1212 search results. Both are unlikely to be in the descriptions of all of those packages and those package pages I tried did not yield a result to CTRL+F and "minutor" or "lutris".

**Comment by barthalion** [comment]
Please report it at https://github.com/flathub/backend/. This repository is about Flatpak website, not Flathub.

**Comment by ls-1N** [comment]
Are you sure? This is an issue when using https://flathub.org/apps search but not when searching the flathub repo via CLI `flatpak search lutris`.

**Comment by mwleeds** [comment]
> Are you sure? This is an issue when using https://flathub.org/apps search but not when searching the flathub repo via CLI `flatpak search lutris`.

flathub.org is separate from flatpak.org so this is the wrong repo for this issue

**Comment by ls-1N** [comment]
Okay, thanks!
