### ISSUE TITLE
Can't update Firefox

### ISSUE THREAD

**Issue by hhradice** [flatpak/flatpak.github.io#493]
I want to update Firefox and discovered that flatpak is the way it is done.  I have tried to follow the directions but the install fails.  I tried to install the flatpak repo but I can't tell if it worked.  I tried to then update firefox but I get a message from a package called 'Software' that the install failed.  How do I update firefix?  Detailed instructions please.

**Comment by mwleeds** [comment]
Hi @hhradice this is the repo for the flatpak.org website, and it's for tracking issues with that. For support you can try asking in the Flatpak matrix channel: https://matrix.to/#/#flatpak:matrix.org

**Comment by hhradice** [comment]
How do I ask a question and get an answer regarding flatpak?  I went to the link provided and there was no place to ask a question.  I could not figure out what the links there were for.  It looked like they wanted me to download some kind of program that I have never heard of.  I WILL NOT download something that could be a virus or something worse.  If this is the type of support for flatpak I will NEVER use flatpak.

**Comment by mwleeds** [comment]
@hhradice Matrix is a protocol that is used to create chat rooms and there are a variety of clients for it. Not all of them require downloading anything; you can use the Web client of Element in your browser. Choose "Continue" then "Continue in your browser" on the page linked above.

**Comment by kludikovsky** [comment]
Still not clear who is target for which kind of issue.
