### ISSUE TITLE
Feeds for ‘recently added applications’ not working

### ISSUE THREAD

**Issue by defenset** [flatpak/flatpak.github.io#497]
![bug_flatpak](https://user-images.githubusercontent.com/94124619/141649552-1099ec75-e6a9-4c32-a69e-0fbf50aa9bc9.png)

but the other one works.

**Comment by mwleeds** [comment]
This is the repo for flatpak.org. You can report flathub issues here: https://github.com/flathub/flathub/issues

**Comment by defenset** [comment]
sorry about that, I just post it [there](https://github.com/flathub/flathub/issues/2637), thanks
