### ISSUE TITLE
Too much whitespace - top of the page

### ISSUE THREAD

**Issue by alexsch01** [flatpak/flatpak.github.io#513]
### How to reproduce

1. Go to https://flatpak.org/
2. Notice that you have to scroll to get to the start of content (including Setup button)

### Expected Behavior

Go to https://flatpak.org/

It should look like this

![image](https://user-images.githubusercontent.com/5721147/150535000-663af91e-a0c1-4a76-b7e5-3a4d7946f841.png)

### Actual Behavior

Go to https://flatpak.org/

It currently (1/21/2022) looks like this when you go to the page

![image](https://user-images.githubusercontent.com/5721147/150535179-2660a83f-35a7-4d1a-910d-dfbdf967a4e8.png)

You have to scroll to get to the actual start of the website

![image](https://user-images.githubusercontent.com/5721147/150535277-71e50f74-993b-4b6c-b307-ec57e4d5d54b.png)

### Additional Information

Tested on Chromium on both Linux and Android

**Comment by alexsch01** [comment]
Tested on Chromium on the desktop and the Android version of Chromium

**Comment by AsciiWolf** [comment]
I am able to reproduce this issue in Chrome on my Android smartphone, however it does not happen in Firefox on my (Fedora) desktop PC.

**Comment by jonsch318** [comment]
I could also reproduce this on Chrome on Ubuntu and Windows. It is the Matomo analytics image tags that is not set to the right height, or the right visibility.

**Comment by mwleeds** [comment]
Ah I think @barthalion is the expert on the matomo stuff

**Comment by razzeee** [comment]
Can you check if your still seeing this? You might need to reload the page with `Strg` + `F5`

**Comment by alexsch01** [comment]
> Can you check if your still seeing this? You might need to reload the page with `Strg` + `F5`

It's fixed now, thank you so much!
