### ISSUE TITLE
Certain Flatpak setup pages ending with / appear to be down

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/flatpak.github.io#517]
For example, https://flatpak.org/setup/Debian/ but https://flatpak.org/setup/Debian works. However, the Fedora and Ubuntu ones appear to work just fine in both cases.

**Comment by phasegen** [comment]
Can confirm, and dropping the slash worked for kubuntu.
https://flatpak.org/setup/Kubuntu\   404'd
https://flatpak.org/setup/Kubuntu  worked

**Comment by Evernow** [comment]
Similar case with Manjaro and RHEL.

**Comment by razzeee** [comment]
Should be all good now

**Comment by razzeee** [comment]
Can we close this?
