### ISSUE TITLE
Fedora Install Guide 404

### ISSUE THREAD

**Issue by marcolaux** [flatpak/flatpak.github.io#521]
Hello and good day,

I just noticed that when I click on Fedora here:

https://flatpak.org/setup/

it gives me a 404

https://flatpak.org/setup/Fedora/

All the best thank you for everything :heart:

**Comment by brokenshield** [comment]
Same for me. Trying to setup on new Silverblue install (Firefox on Gnome 41). 

Edit: Correction, actually only Ubuntu seems to be working. All other distros are giving a 404 error.

**Comment by haggen88** [comment]
#517  related

**Comment by razzeee** [comment]
Should be fixed

**Comment by brokenshield** [comment]
> Should be fixed

Confirmed by this user. The Fedora link from the main page: 
https://flatpak.org/setup/  

now goes to the correct link:
https://flatpak.org/setup/Fedora

Thank you 😊

**Comment by ArchWizard56** [comment]
It seems to work on the website now, but Google search results still seem to point to pages with the trailing slash, causing a 404. Perhaps a rule in the nginx config to remove the trailing slashes is a good solution.

**Comment by mwleeds** [comment]
Google search results seem to work

**Comment by razzeee** [comment]
Yes, I had barthalion add the needed nginx rule. Forget to mention here.

**Comment by razzeee** [comment]
And there is a problem with some links, as escaping seems to be broken.

Reported it here https://github.com/middleman/middleman/issues/2535
