### ISSUE TITLE
Show & link Mastodon social icons from the website's footer (also, eliminate account confusion?)

### ISSUE THREAD

**Issue by nekohayo** [flatpak/flatpak.github.io#527]
Apparently [FlatpakApps on Fosstodon](https://fosstodon.org/@FlatpakApps) is the [official](https://twitter.com/FlatpakApps/status/1450178134804873222) non-twitter source of news, but there was also [@flatpakappsnews@mastodon.social](https://mastodon.social/@FlatpakAppsNews); apparently the 2nd one is not official, and [supposed to be abandoned](https://mastodon.social/@rcmainak/103833844857772432) due to insufficient resources to run its bot, yet it still seems to run past its deadline...

In any case, this is confusing and these accounts are very hard to find, thanks to Mastodon not offering any user search features (especially not cross-instances), so it/they should at least be linked prominently from the website's footer.

**Comment by razzeee** [comment]
The mastodon account has been linked for some time, this can be closed
