### ISSUE TITLE
mention systemd --user and cgroups

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#53]
The technologies section should perhaps mention systemd --user and cgroups.

We may also want to add a list of dependencies / prerequisites somewhere.

**Comment by allanday** [comment]
The wiki has a small section on host requirements. This could be used as a starting point:

https://github.com/flatpak/flatpak/wiki#host-system-requirements

**Comment by matthiasclasen** [comment]
Thanks, I've updated that wiki page to list some more.

**Comment by matthiasclasen** [comment]
also added a mention to the website now

**Comment by alexlarsson** [comment]
This is not needed anymore starting in 0.6.10
