### ISSUE TITLE
Pisi GNU/Linux instructions broken

### ISSUE THREAD

**Issue by ScottScott0** [flatpak/flatpak.github.io#530]
How to replicate:
1. Open Firefox (version 99.0.1)
2. Open [https://flatpak.org/setup/](https://flatpak.org/setup/)
3. Click on the Pisi GNU/Linux logo.
4. Observe it not loading. ("The page isn’t redirecting properly")

**Comment by razzeee** [comment]
I think this has been fixed a long time ago
