### ISSUE TITLE
flatpak.org ux design is bad

### ISSUE THREAD

**Issue by mu-us61** [flatpak/flatpak.github.io#536]
%99 of website visitors is there to go to app repo but it is actually is at the footer on the website this is really bad at least from my perspective

![asdasdf](https://user-images.githubusercontent.com/73366454/168924311-28f0d872-5b61-4443-913e-ce4c71a36021.png)

**Comment by AsciiWolf** [comment]
Well, Flathub is just one of the Flatpak repositories, not the only one. :-)

**Comment by flexagoon** [comment]
People who want to go to Flathub can just directly visit flathub.org

**Comment by mwleeds** [comment]
There's also a link to Flathub on the first screen of the page, not just in the footer
