### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by tiagogaspar8** [flatpak/flatpak.github.io#550]
Hi all,

I would like to ask for IPv6 support for flatpak, I didn't see any other place to do hence why I'm creating an issue. I've investigated and can see that it's being served by a Red Hat Network (from its addresses) and Red Hat currently has an IPv6 block so this can be possible. Any help you need I'm on it!

Thanks! 😄

**Comment by razzeee** [comment]
This is the repo for the website flatpak.org - it has nothing to do with flatpak itself or flatpak remotes.

Please close this
