### ISSUE TITLE
Kali Linux Flatpak remote-add Error

### ISSUE THREAD

**Issue by mxvproject** [flatpak/flatpak.github.io#552]
(flatpak remote-add:110886): GLib-GIO-CRITICAL **: 15:12:37.552: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed

![image](https://user-images.githubusercontent.com/111507231/187385929-4e1bf1e1-97b7-4d21-9b8e-0b94a519648a.png)

**Comment by AsciiWolf** [comment]
Hmm. Did you try running `flatpak repair` or rebooting the computer?

**Comment by AsciiWolf** [comment]
Anyway, this not a correct place to report issues of Flatpak itself. This tracker is for the Flatpak.org website issues. The correct place is [here](https://github.com/flatpak/flatpak/issues).
