### ISSUE TITLE
Make a button for copypasting setup commands

### ISSUE THREAD

**Issue by KralaBenjamin** [flatpak/flatpak.github.io#559]
I followed the setup page on https://flatpak.org/setup/Ubuntu
and once I miscopied one line of command.

On other pages of flathub page you can copypaste the command (e.g. application page, https://flathub.org/apps/details/org.gnome.gitlab.somas.Apostrophe)
It would be wonderful if you can do it also on the setup page.

**Comment by razzeee** [comment]
This site has had a copy button for some time, this can be closed
