### ISSUE TITLE
Suggested content

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#58]
Here are some questions that I think might be good to answer, either on the website itself, or as an faq:
- Can flatpak be used for servers too ?
- How does flatpak compare to other application sandboxing technologies: zeroinstall, glick, snap, ... ?
- How does flatpak compare to other packaging technologies: rpm, dep,... ?
- Which runtime should I use for my app ?
- What about security updates ?

**Comment by jimmac** [comment]
FAQ sounds appropriate, but perhaps security updates (frequent argument for distros) is an area we should emphasize. If we have a good story there, that is :)

**Comment by alexlarsson** [comment]
> Can flatpak be used for servers too ?

Flatpak is designed to run inside a desktop session, and relies on certain session services being there, such as a dbus session bus and a systemd --user instance. So, is not a good match for a server.

However, the build features of flatpak run fine outside a session, so you can build things on a server.

>  How does flatpak compare to other application sandboxing technologies: zeroinstall, glick, snap, ... ?

This is complicated to answer. I'm not sure we want to go through the pain of doing comparison to all of these.

**Comment by allanday** [comment]
"Which runtime should I use for my app ?" is covered by the updated runtime page - http://flatpak.org/runtimes.html

**Comment by allanday** [comment]
I've created issue #227 and #228 to track the remaining parts of this.
