### ISSUE TITLE
Add setup instructions for RHEL

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#59]
An omission from the "Getting flatpak" section: RHEL. Do we want to say something about it ?

**Comment by allanday** [comment]
> An omission from the "Getting flatpak" section: RHEL. Do we want to say something about it ?

I don't see why we shouldn't. What would the instructions be?

**Comment by matthiasclasen** [comment]
$ dnf install flatpak
$ flatpak remote-add --if-not-exist flathub https://flathub.org/repo/flathub.flatpakrepo

**Comment by allanday** [comment]
That's RHEL 7, I assume? Is it possible to install the gnome-software flatpak plugin?

**Comment by matthiasclasen** [comment]
It appears we have flatpak support in gnome-software out-of-the-box since 7.4

**Comment by allanday** [comment]
Fixed - https://flatpak.org/setup/Red%20Hat%20Enterprise%20Linux/
