### ISSUE TITLE
New builds not deployed

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak.github.io#616]
It looks like that none of the changes in last commits is actually live on Flatpak.org. Maybe there are some (server-side) cache issues?

**Comment by AsciiWolf** [comment]
It looks like that there is still the same problem.

@barthalion Any idea?

**Comment by barthalion** [comment]
Should be fixed now. Mind double-checking @AsciiWolf?

**Comment by AsciiWolf** [comment]
It looks like that it got updated now, thanks! :-)

By the way, I have noticed [this warning](https://github.com/flatpak/flatpak.github.io/actions/runs/5809574404/job/15748622081#step:4:14) in the latest build. But it does not seem to cause any issues.

Closing this ticket.
