### ISSUE TITLE
Manjaro Linux Firefox will not save files

### ISSUE THREAD

**Issue by ImConfused3** [flatpak/flatpak.github.io#627]
I tried all versions for installation. The Flatpak FIrefox showed Netflix shows but failed when I had to save files. I installed it because of Netflix but the file savings was the first I tried to use it for that function. On the original firefox which didn't show Netflix it saved files fine.

**Comment by AsciiWolf** [comment]
This issue tracker is for the Flatpak.org website. Your issue should be reported [here](https://bugzilla.mozilla.org).
