### ISSUE TITLE
Update Setup Flathub Distro Pages

### ISSUE THREAD

**Issue by RacerBG** [flatpak/flatpak.github.io#629]
From: https://github.com/flathub/website/issues/1887

I looked through all the available distributions in the Flathub setup page and noticed the following issues:

For the Debian page:

Delete "_For Debian Jessie and Stretch, a flatpak package is available in the [official backports repository](https://backports.debian.org/Instructions/)._" because both Jessie and Stretch are no longer supported (they are in ELTS which is not official support).

Add information about the plasma-discover-backend-flatpak. For example:

"_If you are running KDE, it is also a good idea to install the Flatpak plugin for Discover. To do this, run:_"

`apt install plasma-discover-backend-flatpak`

For the Pisi GNU/Linux page:

The page just gives a 404 error.

Thanks in advance!

**Comment by AsciiWolf** [comment]
Thanks for all the suggestions!

P.S. The Pisi GNU/Linux page seems to work fine in my browser.

**Comment by RacerBG** [comment]
> Thanks for all the suggestions!
> 
> P.S. The Pisi GNU/Linux page seems to work fine in my browser.

For context, I'm using Firefox ESR 115.2.0.

**Comment by razzeee** [comment]
The Pisi GNU/Linux page only seems to be broken on the flathub side of things, I think

**Comment by AsciiWolf** [comment]
The Pisi GNU/Linux page seems to work fine on Flathub as well for me.

**Comment by razzeee** [comment]
> The Pisi GNU/Linux page seems to work fine on Flathub as well for me.

Yeah, I've patched it yesterday :)
https://github.com/flathub/website/commit/bba8f8f8361118973f61bb25f42dddaa48505ee4

**Comment by RacerBG** [comment]
> > The Pisi GNU/Linux page seems to work fine on Flathub as well for me.
> 
> Yeah, I've patched it yesterday :) [flathub/website@bba8f8f](https://github.com/flathub/website/commit/bba8f8f8361118973f61bb25f42dddaa48505ee4)

The Pisi GNU/Linux page is now fine for me too.

Only the Debian part of this issue remains. :smiley_cat:

**Comment by AsciiWolf** [comment]
> Only the Debian part of this issue remains. 😺

#630 ;-)
