### ISSUE TITLE
Flatpack steam longer has permission to install games no matter what I do to allow it

### ISSUE THREAD

**Issue by BlackStark62** [flatpak/flatpak.github.io#637]
I am currently running Linux mint 21.1 vera and one of the recent update to the flatpack version of steam has made it so that I cannot install games to my secondary drive where I intend to store them. During this process I also discovered that the  repository version of lutris no longer allows the ea app to install and displays an error code 256 which I discerned is a core fonts error (even if you clear and re install, I tried this already.) I am able to do the install to the appropriate drive using the repository version of steam and the flatpack version of lutris. When I launch The Sims 4 the game launches but it hangs on the 'link to EA screen' where I am supposed to log in to EA to play the game. The game reports the status of running but, is clearly not launching correctly on steam. Conversely I am able to launch the game on EA app but despite the accounts being linked the game will not download the content I have purchased on steam so I cannot play the game properly on the EA App either.

**Comment by AsciiWolf** [comment]
Thank you for reporting your issue. This issue tracker is however for the Flatpak.org website. Your issue should be reported [here](https://github.com/flatpak/flatpak/issues) instead.

**Comment by AsciiWolf** [comment]
Also, issues related to Flatpak versions of Steam and Lutris should be reported to their own issue trackers:
https://github.com/flathub/com.valvesoftware.Steam/issues
https://github.com/flathub/net.lutris.Lutris/issues
