### ISSUE TITLE
Feature request]: recommend foss alternatives (or just alternatives in general)

### ISSUE THREAD

**Issue by RustoMCSpit** [flatpak/flatpak.github.io#640]
say i want discord, flatpak will recommend webcord (a foss frontend), element or something else. you get the gist. also ability to scan your system and detect apps with foss alternatives and then tell you the pros and cons between the two

**Comment by AsciiWolf** [comment]
Thanks for your suggestion. This however should be reported [here](https://github.com/flatpak/flatpak/issues) as a feature request. The flatpak.github.io issue tracker is for the Flatpak.org website.
