### ISSUE TITLE
Replace Atom in featured apps with a well known app with nice visual identity

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak.github.io#644]
https://github.com/flatpak/flatpak.github.io/blob/source/data/apps.yml#L61

https://github.blog/2022-06-08-sunsetting-atom/

/cc @jimmac

**Comment by AsciiWolf** [comment]
I would prepare a Pull Request, however I am not sure what color to use.

**Comment by jimmac** [comment]
On a second thought, perhaps a high visibility free software poject might be a better pick. Thunderbird has a decent rebrand behind it and might look nice.

**Comment by AsciiWolf** [comment]
I would personally prefer some developer-focused project as a replacement for Atom in this list. But that's just my personal opinion.

Anyway, we already have two messaging-focused apps in that list, two artist-focused apps, one music-focused app and one gaming-focused app.

Visual Studio Code seems like a good fit to me since it is well known and widely used by many developers and hobbyists + it is usually not available in regular (RPM/DEB) repositories.

**Comment by AsciiWolf** [comment]
Another interesting project to replace Atom with could be [OBS Studio](https://flathub.org/cs/apps/com.obsproject.Studio). ;-)

**Comment by jimmac** [comment]
You literally couldn't pick a project with a worse logo.

**Comment by AsciiWolf** [comment]
Well, I agree that its logo is not ideal. :-) But OBS (except its icon) is still more suitable than Thunderbird in my opinion. We probably want some big project (over 1M or at least 500k users) that is among the [popular apps](https://flathub.org/apps/collection/popular/1) on Flathub and is ideally also an official, verified app on Flathub. Bonus points if such app is not easily available in standard (RPM/DEB) distribution package repositories. :-)

Thunderbird is great, well known and widely used app and has a good looking logo, the problem is that, as I pointed out in my previous comments, we already have two messaging-focused apps in the list.

**Comment by jimmac** [comment]
If we listed projects by name, I'd wholeheartedly support it. But this is meant as a visual anchor and we'd be shooting ourselves in the foot here.

**Comment by bertob** [comment]
I agree that we should pick something with a good icon, since that it's how it shows up on the page. If you're looking for a developer tool, maybe Workbench?

**Comment by AsciiWolf** [comment]
Workbench currently has 35k installs on Flathub and is not something well known and used by majority of developers.

What about [Podman Desktop](https://flathub.org/apps/io.podman_desktop.PodmanDesktop)? It currently has only 86k installs, but is a thing that targets wide group of developers (just like Docker) and the Flatpak is officially supported by Red Hat.

**Comment by AsciiWolf** [comment]
Or we could add [Lutris](https://flathub.org/cs/apps/net.lutris.Lutris). There already is one gaming-related app (Steam) in the list, but Lutris is also very popular (almost 1.4M installs), verified Flatpak and has good looking icon.

Or [Firefox](https://flathub.org/cs/apps/org.mozilla.firefox), also verified and has 4.2M installs.

**Comment by AsciiWolf** [comment]
Maybe Firefox could be the best fit. It is a very well known and widely used app that has a good looking icon.

@jimmac @bertob What do you think?

**Comment by bertob** [comment]
If popularity is important you can't go wrong with Firefox :+1:

**Comment by jimmac** [comment]
Firefox is an obvious choice if we're fine with a non dev tool.

**Comment by jimmac** [comment]
I was going to prepare a patch but getting middleman from back in the day running locally turned out to be a nut too hard to crack. Even after numerous attempts at either running an older container with ruby 2.7 or trying to update middleman I am not victorious. While the [os-component rewrite was binned](https://github.com/flatpak/flatpak.github.io/issues/487), a rewrite using some modern tool is probably inevitable.
