### ISSUE TITLE
Two commands on the same line

### ISSUE THREAD

**Issue by xerxeslins** [flatpak/flatpak.github.io#658]
The two commands to install deepin themes both appear on the same line in the browser. Copying them as is doesn't work. They need to be on separate lines.

![image](https://github.com/flatpak/flatpak.github.io/assets/7513301/63e5fc55-e820-4057-8171-60544e97cfbd)

Default Deepin OS Browser:
6.3.8 64 bits| 93.0.4577.63
Browser
Copyright 2023 UnionTech Software Technology Co., LTD. All Rights Reserved.
This browser is made possible by the Chromium open source project and other open source software.

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I see that [Ubuntu](https://flatpak.org/setup/Ubuntu) (and probably other distributions) also has the same issue.

/cc @razzeee

**Comment by razzeee** [comment]
That was already broken, before I touched it, so I was unsure, if I should change it/if it's actually broken

**Comment by AsciiWolf** [comment]
That's strange. I remember it not being broken. Anyway, it definitely should be fixed.
