### ISSUE TITLE
Aplication don't show windows

### ISSUE THREAD

**Issue by dhhdhshdja** [flatpak/flatpak.github.io#666]
When I try to start apps (from GUI or terminal) it starts, and try to show window. Appears transparent window (I see only shadow) and it auto closes. Other apps (like AnyDesk, Telegram) works, but crashes on dialog windows. Games also don't work properly.
OS: Debian 12
DE: KDE Plasma (X11)
Flatpak: 1.14.4

**Comment by AsciiWolf** [comment]
Thanks for your bug report. This tracker is for the Flatpak website. Your issue should be reported [here](https://github.com/flatpak/flatpak/issues).
