### ISSUE TITLE
Update ChromeOS installation page

### ISSUE THREAD

**Issue by BurtCrepeault** [flatpak/flatpak.github.io#668]
The procedure described at [https://flatpak.org/setup/Chrome%20OS](https://flatpak.org/setup/Chrome%20OS) fails on my system.

Symptom:

> burtcrepeault@penguin:~$ sudo apt install flatpack
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package flatpack

Build information:

> Google Chrome: Version 122.0.6261.118 (Official build)  (64 bits)
> Platform: 15753.46.0 (Official Build) stable-channel brya
> Channel: stable-channel
> Firmware Version: Google_Kano.14505.575.0
> ARC Enabled: true
> ARC: 11541245
> Enterprise Enrolled: false
> Developer Mode : false

**Comment by AsciiWolf** [comment]
Because you have a typo in your apt command. It's `flatpak`, not `flatpack`.
