### ISSUE TITLE
End of life issues

### ISSUE THREAD

**Issue by coolhandluke57** [flatpak/flatpak.github.io#675]
It appears that your Master PDF Editor (net.codeindustry.MasterPDFEditor version 5.9.82) found in LinuxMint Software Manager uses runtime org.kde.Platform//5.15-22.08 which has reached end-of-life.

It appears that your Guiscrcpy (in.srev.guiscrcpy version 4.11.3) found in LinuxMint Software Manager uses runtime org.kde.Platform//5.15-21.08 which has reached end-of-life.

It appears that your Kdeconnect (com.github.bajoja.indicator-kdeconnect version 21.12.3-0ubuntu1) found in LinuxMint Software Manager uses runtime org.gnome.Platform//3.36 which has reached end-of-life.

**Comment by AsciiWolf** [comment]
This should have been reported [here](https://github.com/flathub/flathub/issues).
