### ISSUE TITLE
"Hello World" tutorial is outdated

### ISSUE THREAD

**Issue by leer10** [flatpak/flatpak.github.io#69]
On the "Build" section of the webpage, the example tutorial works fine until the user is instructed to run "flatpak build-export repo hello". The user then sees the output "error: Build directory hello not initialized". I believe that the user isn't supposed to get this error message.

Page in question: http://flatpak.org/#developers 
[log.txt](https://github.com/flatpak/flatpak.github.io/files/313116/log.txt)

**Comment by alexlarsson** [comment]
Did you do paragraph 3? That creates the "hello/export" directory, and the build-export reporting it not being initialized means that it can't find that directory.

**Comment by leer10** [comment]
My mistake then! I didn't know that I was supposed to run the command from its parent directory!
