### ISSUE TITLE
flatpak not installing

### ISSUE THREAD

**Issue by justintime2k** [flatpak/flatpak.github.io#693]
So i have this problem, where Flatpack refuses to install. Im on the steam deck, ergo arch. 
![image](https://github.com/user-attachments/assets/7d8e019f-8b84-4d64-ba22-e77d90cdeaeb)

**Comment by AsciiWolf** [comment]
1. SteamOS is an immutable system that is read-only (except /home) by default.
2. Flatpak is already installed on SteamOS.
3. This is a bug tracker for the Flatpak.org website.

Closing this ticket.
