### ISSUE TITLE
Flatpak-builder tutorial: Failed to execute child process "eu-strip"

### ISSUE THREAD

**Issue by leer10** [flatpak/flatpak.github.io#70]
I attempted to follow "Building More Complex Apps With flatpak-builder" and everything was running smoothly (making the json, executing flatpak-builder) until it hit an error whose scrollback I've posted. I did verify that I had 3.20 runtime and sdk installed.

[flatpakbuilder.txt](https://github.com/flatpak/flatpak.github.io/files/314850/flatpakbuilder.txt)

**Comment by leer10** [comment]
Extra background info: running Kubuntu 16.04 with KDE neon. Using the 16.04 ppa of flatpak

**Comment by leer10** [comment]
I'm an idiot cause I didn't install elfutils on my computer. Possibly add a bit about how it is needed?

**Comment by alexlarsson** [comment]
Seems like a ppa packaging issue. flatpack-builder should depend on elfutils.

**Comment by jimmac** [comment]
In any case, it's not an issue with the website. I hope you don't mind me closing and hoping for a follow through in Ubuntu bug tracker...
