### ISSUE TITLE
Feature the Firefox Nightly flatpaks

### ISSUE THREAD

**Issue by jimmac** [flatpak/flatpak.github.io#73]
Apparently Vadim Rutkovsky has been buidling Firefox nightlies. We should point to them on the apps page.

**Comment by jimmac** [comment]
Correction: Not building nighties, just set up scripts to build nightlies -- https://github.com/vrutkovs/firefox-flatpak

**Comment by allanday** [comment]
There is the Developer Edition Flatpak. There's a flatpakref for this here:

https://firefox-flatpak.mojefedora.cz/firefox-devedition.flatpakref

(See https://firefox-flatpak.mojefedora.cz/ )

**Comment by allanday** [comment]
flatpak.org doesn't link to apps any more, and we're generally focused on flathub as the place to get apps. I assume we don't need this issue any more, but just reopen if we do.
