### ISSUE TITLE
mention mageia flatpak support

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak.github.io#76]
Son_Goku>	alexlarsson, so JFYI, Mageia now has Flatpak in Cauldron as of this morning
it'll be part of the Mageia 6 release
 7∶56 PM
it can be installed the same way it is on Fedora
as root, running "dnf install flatpak"
or, if using urpmi (the current default package manager), running "urpmi flatpak"

**Comment by jimmac** [comment]
Added in fa5bff0347021b16c6748d5e30bfa235090e1629
