### ISSUE TITLE
Improve spacing for code sections

### ISSUE THREAD

**Issue by palasso** [flatpak/flatpak.github.io#8]
While the spacing is good before a code section begins, it's very short after a code section ends. The end result is not that nice and in parts of the documentation it's a bit confusing.

![screenshot_20160522_112452](https://cloud.githubusercontent.com/assets/5258956/15453091/11e28c94-2010-11e6-88a1-be17cbf4d6c8.png)

It would be nice if the spacing after a code section ends were increased to at least match the spacing before a code section begins and maybe be 50% more.

Alternatively it might be better to reduce a little the spacing before a code section begins and increase the spacing after a code section ends to what the spacing is now for before a code section begins.

**Comment by jimmac** [comment]
uniform margins for pre commited.
