### ISSUE TITLE
Get involved section navigation is confusing 

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak.github.io#86]
When clicking "Get Involved" - http://flatpak.org/index.html#get-involved the section is small enough to actually not display Get Involved as the first thing on the page, which makes it confusing. I would consider putting an image (GNOME community or something?) as part of that section to both give a feeling of community and to fix the scroll issue. You can see what I mean here:
![screenshot from 2016-08-19 10-30-37](https://cloud.githubusercontent.com/assets/1755514/17803641/fd678df4-65f7-11e6-98e2-2f11fe2187c7.png)

**Comment by jimmac** [comment]
I might even have some appropriate photos from GUADEC.

**Comment by allanday** [comment]
This issue was one reason why we replaced Get Involved with a simple contact section in the recent website update.
