### ISSUE TITLE
Supporting Project Logos

### ISSUE THREAD

**Issue by jimmac** [flatpak/flatpak.github.io#90]
We should feature projects that support Flatpak prominently.

**Comment by andreasn** [comment]
Do you have a list of those projects?

**Comment by jimmac** [comment]
The newly redesigned site is set to feature supported distros and OSes. https://github.com/flatpak-design-team/flatpak-website-mockups/blob/master/flatpak.org-960.png

**Comment by allanday** [comment]
> The newly redesigned site is set to feature supported distros and OSes. https://github.com/flatpak-design-team/flatpak-website-mockups/blob/master/flatpak.org-960.png

Yea, I think this is enough.
