### ISSUE TITLE
Semi-transparent topbar covers headings

### ISSUE THREAD

**Issue by baedert** [flatpak/flatpak.github.io#93]
This seems to work for most of the anchors on flatpak.org, but the svg under "How it works" links to the Library/Sandbox sections right below it and clicking on such a link will scroll to it correctly, but now the semi-transparent topbar the heading as well as the first line of the paragraph so one has to immediately scoll up again.

**Comment by jimmac** [comment]
Initially I thought this was about the header covering up a heading, but after re-reading your issue I'm quite confused. Can you elaborate on this a bit more? Is this about being able to scroll back to the graphic?

**Comment by baedert** [comment]
> Initially I thought this was about the header covering up a heading

It was exactly that but now I found out that it was due to disabled javascript, so we can close this one.
