### ISSUE TITLE
Add info about how to debug flatpak applications

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak.github.io#97]
I'm currently experiencing that one of my installed flatpaks aren't running. it would be nice if the website had a section inside "Build" for "Debugging flatpaks". Stuff like how to get a shell into the sandbox, how to check what permissions the flatpak has, how to find out what dependencies are available in the runtime etc.

**Comment by allanday** [comment]
The docs are now hosted in the flatpak-docs repo, and this issue is superceded by https://github.com/flatpak/flatpak-docs/issues/11
